openapi: 3.2.0
info:
  title: Harness Costs API
  version: '1.0'
  description: The Harness Software Delivery Platform uses OpenAPI Specification v3.0.
  contact:
    name: API Support
    email: contact@harness.io
    url: https://harness.io/
  x-logo:
    url: https://mma.prnewswire.com/media/779232/Harnes_logo_horizontal.jpg?p=facebook
    altText: Harness
  termsOfService: https://harness.io/terms-of-use/
servers:
- url: https://app.harness.io
  description: Harness host URL
- url: https://{vanity}
  description: Vanity URL
  variables:
    vanity:
      default: app.harness.io
security:
- x-api-key: []
tags:
- name: Costs
  description: 'Costs Service handles the API related with the costs attached to workspaces.

    This API is read only as all the cost are generated in the plugin side'
paths:
  /iacm/api/orgs/{org}/projects/{project}/costs:
    get:
      tags:
      - Costs
      summary: List costs
      description: List the monthly cost per each workspace
      operationId: costs#list-costs
      parameters:
      - name: start_time
        in: query
        description: Specify the start time for the query
        allowEmptyValue: true
        schema:
          type: integer
          description: Specify the start time for the query
          example: 1691150743950
          format: int64
        example: 1691150743950
      - name: end_time
        in: query
        description: Specify the end time limit for the query
        allowEmptyValue: true
        schema:
          type: integer
          description: Specify the end time limit for the query
          example: 1691150743950
          format: int64
        example: 1691150743950
      - name: page
        in: query
        description: Page is the page number to return relative to the page 'limit'.
        allowEmptyValue: true
        schema:
          type: integer
          description: Page is the page number to return relative to the page 'limit'.
          default: 1
          example: 1
          format: int64
          minimum: 1
        example: 1
      - name: limit
        in: query
        description: Limit is the number of records to return for a page.
        allowEmptyValue: true
        schema:
          type: integer
          description: Limit is the number of records to return for a page.
          default: 30
          example: 30
          format: int64
          minimum: 1
          maximum: 1000
        example: 30
      - name: workspaces
        in: query
        description: Filter the workspaces to retrieve the cost
        allowEmptyValue: true
        schema:
          type: array
          items:
            type: string
            example: Eos corporis rerum.
          description: Filter the workspaces to retrieve the cost
          example:
          - Quia ut dolor qui.
          - Consequatur hic ad distinctio quia consequatur voluptatem.
          - Eveniet ducimus repellendus similique nesciunt facilis.
        example:
        - Quas magni aut aut ad occaecati.
        - Sunt dolorum neque.
        - Autem illo.
        - Minus in nihil reprehenderit consectetur corrupti consequatur.
      - name: org
        in: path
        description: Org is the organisation identifier.
        required: true
        schema:
          type: string
          description: Org is the organisation identifier.
          example: 6y
          minLength: 1
          maxLength: 128
        example: t
      - name: project
        in: path
        description: Project is the project identifier.
        required: true
        schema:
          type: string
          description: Project is the project identifier.
          example: z4
          minLength: 1
          maxLength: 128
        example: ob
      - name: Harness-Account
        in: header
        description: Account is the internal customer account ID.
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Account is the internal customer account ID.
          example: kwy
          minLength: 1
          maxLength: 128
        example: 8f
      responses:
        '200':
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCostsResponse'
              example:
                pageSize: 50
                totalItems: 1800
                totalPages: 36
                workspaces:
                - cost: '12.13'
                  created: 1672531200
                  currency: USD
                  workspace_id: Unde qui ab rerum.
                  workspace_name: Aperiam sapiente hic.
                - cost: '12.13'
                  created: 1672531200
                  currency: USD
                  workspace_id: Unde qui ab rerum.
                  workspace_name: Aperiam sapiente hic.
                - cost: '12.13'
                  created: 1672531200
                  currency: USD
                  workspace_id: Unde qui ab rerum.
                  workspace_name: Aperiam sapiente hic.
                - cost: '12.13'
                  created: 1672531200
                  currency: USD
                  workspace_id: Unde qui ab rerum.
                  workspace_name: Aperiam sapiente hic.
        '400':
          description: 'BadRequestError: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '401':
          description: 'UnauthorizedError: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '403':
          description: 'ForbiddenError: Forbidden response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '404':
          description: 'NotFoundError: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '408':
          description: 'TimeoutError: Request Timeout response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '409':
          description: 'ConflictError: Conflict response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '423':
          description: 'LockedError: Locked response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '499':
          description: 'ContextCancelledError:  response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '500':
          description: 'InternalServerError: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '502':
          description: 'BadGatewayError: Bad Gateway response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
  /iacm/api/orgs/{org}/projects/{project}/costs/{workspace}:
    get:
      tags:
      - Costs
      summary: List costs per workspace
      description: List the cost of the workspace and correlate it with the executions
      operationId: costs#list-costs-per-workspace
      parameters:
      - name: limit
        in: query
        description: Limit is the number of records to return for a page.
        allowEmptyValue: true
        schema:
          type: integer
          description: Limit is the number of records to return for a page.
          default: 30
          example: 30
          format: int64
          minimum: 1
          maximum: 1000
        example: 30
      - name: page
        in: query
        description: Page is the page number to return relative to the page 'limit'.
        allowEmptyValue: true
        schema:
          type: integer
          description: Page is the page number to return relative to the page 'limit'.
          default: 1
          example: 1
          format: int64
          minimum: 1
        example: 1
      - name: start_time
        in: query
        description: Specify the start time for the query
        allowEmptyValue: true
        schema:
          type: integer
          description: Specify the start time for the query
          example: 1691150743950
          format: int64
        example: 1691150743950
      - name: end_time
        in: query
        description: Specify the end time limit for the query
        allowEmptyValue: true
        schema:
          type: integer
          description: Specify the end time limit for the query
          example: 1691150743950
          format: int64
        example: 1691150743950
      - name: org
        in: path
        description: Org is the organisation identifier.
        required: true
        schema:
          type: string
          description: Org is the organisation identifier.
          example: gi
          minLength: 1
          maxLength: 128
        example: ix
      - name: project
        in: path
        description: Project is the project identifier.
        required: true
        schema:
          type: string
          description: Project is the project identifier.
          example: u
          minLength: 1
          maxLength: 128
        example: f7b
      - name: workspace
        in: path
        description: Workspace id to retrieve the cost and the metadata associated with it
        required: true
        schema:
          type: string
          description: Workspace id to retrieve the cost and the metadata associated with it
          example: Et et et.
        example: Totam dolor sit.
      - name: Harness-Account
        in: header
        description: Account is the internal customer account ID.
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Account is the internal customer account ID.
          example: c
          minLength: 1
          maxLength: 128
        example: '201'
      responses:
        '200':
          description: OK response.
          headers:
            x-page-size:
              description: Current page size
              schema:
                type: integer
                description: Current page size
                example: 50
                format: int64
              example: 50
            x-total-items:
              description: Total items available
              schema:
                type: integer
                description: Total items available
                example: 1800
                format: int64
              example: 1800
            x-total-pages:
              description: Total pages available
              schema:
                type: integer
                description: Total pages available
                example: 36
                format: int64
              example: 36
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CostResourceCollection'
              example:
              - account: dl
                activity_type: apply
                cost: '12.13'
                created: 1672531200
                currency: USD
                org: id5
                pipeline: Similique consequatur veritatis id nam.
                pipeline_execution_id: Debitis eos dolorem voluptatibus.
                pipeline_stage_id: Omnis nesciunt fuga dolores est.
                project: 1c
                workspace: Asperiores dolorem qui laborum est.
              - account: dl
                activity_type: apply
                cost: '12.13'
                created: 1672531200
                currency: USD
                org: id5
                pipeline: Similique consequatur veritatis id nam.
                pipeline_execution_id: Debitis eos dolorem voluptatibus.
                pipeline_stage_id: Omnis nesciunt fuga dolores est.
                project: 1c
                workspace: Asperiores dolorem qui laborum est.
        '400':
          description: 'BadRequestError: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '401':
          description: 'UnauthorizedError: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '403':
          description: 'ForbiddenError: Forbidden response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '404':
          description: 'NotFoundError: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '408':
          description: 'TimeoutError: Request Timeout response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '409':
          description: 'ConflictError: Conflict response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '423':
          description: 'LockedError: Locked response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '499':
          description: 'ContextCancelledError:  response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '500':
          description: 'InternalServerError: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '502':
          description: 'BadGatewayError: Bad Gateway response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
components:
  schemas:
    HarnessIacmCostsresources:
      type: object
      properties:
        account:
          type: string
          description: Account is the internal customer account ID.
          example: 30w
          minLength: 1
          maxLength: 128
        activity_type:
          type: string
          description: The type of activity that generated this cost (e.g. apply, plan, destroy)
          example: apply
        cost:
          type: string
          description: The cost associated to the execution metadata
          example: '12.13'
        created:
          type: integer
          description: The epoch time for the cost
          example: 1672531200
          format: int64
        currency:
          type: string
          description: The currency for the cost
          example: USD
        org:
          type: string
          description: Org is the organisation identifier.
          example: h3
          minLength: 1
          maxLength: 128
        pipeline:
          type: string
          description: The unique identifier for the associated pipeline
          example: Sint eos quis quis et nobis.
        pipeline_execution_id:
          type: string
          description: The unique identifier for the associated pipeline execution
          example: Quas vel quos eum est.
        pipeline_stage_id:
          type: string
          description: The unique identifier for the associated pipeline stage
          example: Assumenda praesentium error sunt cupiditate.
        project:
          type: string
          description: Project is the project identifier.
          example: bb0
          minLength: 1
          maxLength: 128
        workspace:
          type: string
          description: The unique identifier for the associated workspace
          example: Tempora facere cum.
      description: CostResource is the representation for a single workspace of the cost and metadata that ties the cost to an execution.
      example:
        account: o
        activity_type: apply
        cost: '12.13'
        created: 1672531200
        currency: USD
        org: nt2
        pipeline: Animi commodi.
        pipeline_execution_id: Omnis aut numquam.
        pipeline_stage_id: Cum deleniti et itaque consectetur modi.
        project: sq9
        workspace: Iste iste est eaque suscipit aut voluptate.
      required:
      - account
      - org
      - project
      - pipeline_execution_id
      - pipeline_stage_id
      - workspace
      - pipeline
      - workspace_id
      - workspace_name
      - currency
      - cost
      - created
    CostResourceCollection:
      type: array
      items:
        $ref: '#/components/schemas/HarnessIacmCostsresources'
      example:
      - account: dl
        activity_type: apply
        cost: '12.13'
        created: 1672531200
        currency: USD
        org: id5
        pipeline: Similique consequatur veritatis id nam.
        pipeline_execution_id: Debitis eos dolorem voluptatibus.
        pipeline_stage_id: Omnis nesciunt fuga dolores est.
        project: 1c
        workspace: Asperiores dolorem qui laborum est.
      - account: dl
        activity_type: apply
        cost: '12.13'
        created: 1672531200
        currency: USD
        org: id5
        pipeline: Similique consequatur veritatis id nam.
        pipeline_execution_id: Debitis eos dolorem voluptatibus.
        pipeline_stage_id: Omnis nesciunt fuga dolores est.
        project: 1c
        workspace: Asperiores dolorem qui laborum est.
      - account: dl
        activity_type: apply
        cost: '12.13'
        created: 1672531200
        currency: USD
        org: id5
        pipeline: Similique consequatur veritatis id nam.
        pipeline_execution_id: Debitis eos dolorem voluptatibus.
        pipeline_stage_id: Omnis nesciunt fuga dolores est.
        project: 1c
        workspace: Asperiores dolorem qui laborum est.
    IaCMError:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      example:
        fault: false
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: false
        timeout: true
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    ListCostsResponse:
      type: object
      properties:
        pageSize:
          type: integer
          description: Current page size
          example: 50
          format: int64
        totalItems:
          type: integer
          description: Total items available
          example: 1800
          format: int64
        totalPages:
          type: integer
          description: Total pages available
          example: 36
          format: int64
        workspaces:
          type: array
          items:
            $ref: '#/components/schemas/HarnessIacmMonthlycost'
          description: Representation of all the workspaces, and cost information
          example:
          - cost: '12.13'
            created: 1672531200
            currency: USD
            workspace_id: Unde qui ab rerum.
            workspace_name: Aperiam sapiente hic.
          - cost: '12.13'
            created: 1672531200
            currency: USD
            workspace_id: Unde qui ab rerum.
            workspace_name: Aperiam sapiente hic.
          - cost: '12.13'
            created: 1672531200
            currency: USD
            workspace_id: Unde qui ab rerum.
            workspace_name: Aperiam sapiente hic.
          - cost: '12.13'
            created: 1672531200
            currency: USD
            workspace_id: Unde qui ab rerum.
            workspace_name: Aperiam sapiente hic.
      example:
        pageSize: 50
        totalItems: 1800
        totalPages: 36
        workspaces:
        - cost: '12.13'
          created: 1672531200
          currency: USD
          workspace_id: Unde qui ab rerum.
          workspace_name: Aperiam sapiente hic.
        - cost: '12.13'
          created: 1672531200
          currency: USD
          workspace_id: Unde qui ab rerum.
          workspace_name: Aperiam sapiente hic.
        - cost: '12.13'
          created: 1672531200
          currency: USD
          workspace_id: Unde qui ab rerum.
          workspace_name: Aperiam sapiente hic.
        - cost: '12.13'
          created: 1672531200
          currency: USD
          workspace_id: Unde qui ab rerum.
          workspace_name: Aperiam sapiente hic.
      required:
      - totalItems
      - totalPages
      - pageSize
    HarnessIacmMonthlycost:
      type: object
      properties:
        cost:
          type: string
          description: The cost associated to the execution metadata
          example: '12.13'
        created:
          type: integer
          description: The epoch time for the cost
          example: 1672531200
          format: int64
        currency:
          type: string
          description: The currency for the cost
          example: USD
        workspace_id:
          type: string
          example: Incidunt et.
        workspace_name:
          type: string
          example: Rem aut eveniet libero.
      description: MonthlyCost is the cost of a workspace per month
      example:
        cost: '12.13'
        created: 1672531200
        currency: USD
        workspace_id: Inventore provident exercitationem ad sunt mollitia placeat.
        workspace_name: Non distinctio culpa aut quidem consequatur facere.
      required:
      - workspace_id
      - workspace_name
      - currency
      - cost
      - created
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
      description: API key is a token provided while making the API calls. This is used to authenticate the client at the exposed endpoint.
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
x-stoplight:
  id: oc91t4vrfnjyi
x-tagGroups:
- name: Organizations
  tags:
  - Organization
- name: Projects
  tags:
  - Org Project
  - Project
- name: Secrets
  tags:
  - Account Secret
  - Org Secret
  - Project Secret
  - Secrets
- name: Connectors
  tags:
  - Account Connector
  - Org Connector
  - Project Connector
  - Connectors
  - GoogleSecretManagerConnector
- name: Roles
  tags:
  - Account Roles
  - Organization Roles
  - Project Roles
  - Roles
- name: Resource Groups
  tags:
  - Account Resource Groups
  - Organization Resource Groups
  - Project Resource Groups
  - Filter Resource Groups
  - Harness Resource Group
  - Zendesk
- name: Role Assignments
  tags:
  - Account Role Assignments
  - Org Role Assignments
  - Project Role Assignments
  - Role Assignments
- name: Platform
  tags:
  - Access Control List
  - Account Banner
  - Account Banner
  - Account Licensed Modules
  - Account License Type
  - Account Webhooks
  - AccountSetting
  - Accounts
  - Analyze Account Access Policy
  - Analyze Organization Access Policy
  - Analyze Project Access Policy
  - ApiKey
  - Audit
  - AuditFilters
  - Authentication Settings
  - Canny
  - Devops Essentials License Data By Account
  - EULA
  - Filter
  - Harness Resource Type
  - Invite
  - IP Allowlist
  - Nextgen Ldap
  - Notification Channels
  - Notification Rules
  - OIDC
  - Oidc-Access-Token
  - Oidc-ID-Token
  - Org Webhooks
  - Permissions
  - Project Webhooks
  - Secret Managers
  - Service Account
  - Setting
  - SMTP
  - Source Code Manager
  - Token
  - User
  - User Group
  - Variables
- name: Delegate
  tags:
  - Agent mTLS Endpoint Management
  - Delegate Download Resource
  - Delegate Group Tags Resource
  - Delegate Setup Resource
  - Delegate Token Resource
- name: Pipelines
  tags:
  - Pipelines
  - Input Sets
  - Approvals
  - Pipeline Execution
  - Pipeline Dashboard
  - Pipeline Input Set
  - Pipeline
  - Pipeline Execution Details
  - Pipeline Execute
  - Pipeline Refresh
  - Pipeline data retention
  - Triggers
  - TriggersEvents
  - Webhook Triggers
  - Webhook Event Handler
  - DryRunPipeline
- name: Artifact Registry
  tags:
  - Registries
  - Artifacts
  - Docker Artifacts
  - Helm Artifacts
  - quarantine
  - Webhooks
  - Spaces
  - Replication
  - Registry V3 - Registries
  - Registry V3 - Packages
  - Registry V3 - Versions
  - Registry V3 - Files
  - Registry V3 - Metadata
  - Registry V3 - Firewall
  - Registry V3 - Transfer
- name: Database DevOps
  tags:
  - Database Schema
  - Database Instance
  - Deployed State
  - Execution Config
  - Migration State
- name: CD
  tags:
  - K8s Release Service Mapping
  - CustomDeployment
  - Environments
  - EnvironmentGroup
  - Infrastructures
  - Usage
  - File Store
  - Service Dashboard
  - ServiceOverrides
  - Rollback
  - tas
- name: Deployment Freeze
  tags:
  - Freeze CRUD
  - Freeze Evaluation
  - Freeze Schema
- name: Services
  tags:
  - Account Services
  - Org Services
  - Project Services
  - Services
- name: Rancher Infrastructures
  tags:
  - Account Rancher Infrastructure
  - Org Rancher Infrastructure
  - Project Rancher Infrastructure
- name: Templates
  tags:
  - Account Template
  - Org Template
  - Project Template
  - Templates
  - Global Templates
- name: GitOps
  tags:
  - Agents
  - Application
  - Applications
  - Certificates
  - Clusters
  - Dashboard Aggregates
  - Dashboards
  - GnuPGP Keys
  - GPG Keys
  - Hosts
  - Project mappings
  - Projects
  - Reconciler
  - Repositories
  - Repository Certificates
  - Repository credentials
  - ValidateHost
- name: GitX
  tags:
  - GitX Webhooks
  - Org Gitx Webhooks
  - Project Gitx Webhooks
- name: CACM
  tags:
  - Anomalies Ignorelist Rule
  - Anomalies
  - BI Dashboards
  - Budgets
  - Budget Groups
  - Cost Categories
  - Cloud Accounts
  - K8S Connectors Metadata
  - Notification Settings v2
  - Overview
  - Data Job Status
  - Recommendation cost settings
  - Unit Metric
  - Anomaly Comments
  - Cloud and AI cost anomaly details
  - Cloud and AI cost anomalies v2
  - Cost Details
  - Currency Preferences
  - External Data Provider
  - AiEngine
  - CACM governance cost settings
  - Governance Enforcement Recommendation APIs
  - Governance Alert
  - Governance Overview
  - Governance Recommendation APIs
  - RuleEnforcement
  - Rule Executions
  - Rule
  - Rule Sets
  - Perspectives Folders
  - Perspective Reports
  - Perspectives
  - Cost Category Jira Project Mapping
  - Recommendations Details
  - Recommendations
  - Recommendation Jira
  - Recommendation Preferences
  - Recommendation Presets
  - Recommendation Servicenow
  - Recommendation Tags
  - Recommendation Ignore List
  - AutoStopping Rules
  - AutoStopping Rules V2
  - AutoStopping Load Balancers
  - AutoStopping Fixed Schedules
  - AutoStopping Alerts
  - Commitment Orchestrator Events APIs
- name: Feature Flags
  tags:
  - API Keys
  - Feature Flags
  - Targets
  - Target Groups
  - Environment Perspectives
  - Anomalies
  - Proxy
  - Tags
- name: SRM
  tags:
  - Monitored Services
  - SLOs dashboard
  - NG SLOs
  - SLOs
  - Downtime
  - Srm Notification
- name: Internal Developer Portal - IDP
  tags:
  - Entities
  - Teams
  - CatalogCustomProperties
  - Scores
  - DataSource
  - KubernetesDataPoints
  - AggregationRules
  - AppConfig
  - PluginInfo
  - LayoutProxy
  - Kinds
  - LayoutsV3
  - LayoutsV4
- name: Environment Management - IDP
  tags:
  - Environment
  - Infrastructure
  - Instance
- name: Custom Dashboards
  tags:
  - aida
  - dashboards
  - downloads
  - embed
  - folders
- name: Policy Management
  tags:
  - dashboard
  - examples
  - policies
  - evaluate
  - evaluations
  - policysets
  - system
- name: Code
  tags:
  - repository
  - status_checks
  - pullreq
  - upload
  - webhook
  - resource
  - rules
  - labels
- name: IaCM
  tags:
  - usage
  - approvals
  - costs
  - executions
  - module-registry
  - workspaces
  - settings
  - tf-standard-backend
  - variables
- name: STO
  tags:
  - Exemptions
  - Issues
  - Scans
  - Products
  - Test Targets
  - Target Variants
- name: SEI
  tags:
  - Collection categories
  - Collections
  - Contributors
  - DORA
- name: Git Sync (deprecated)
  tags:
  - Git Branches
  - Git Full Sync
  - Git Sync Settings
  - Git Sync
  - Git Sync Errors
- name: Error Models
  tags:
  - Error Response
  - Governance Metadata
- name: Supply Chain Security
  tags:
  - integration
  - PipelineInfraConfig
  - SBOM
  - Integration Step Config
  - Delete Step Config
  - Delete Repositories
  - Pipeline Store Config
  - Evidence Vault [Beta]
- name: Release Management
  tags:
  - Release Groups
  - Releases
  - Orchestration Processes
  - Orchestration Activities
  - Orchestration Executions
  - Conflicts
  - Freeze
  - Reports
  - Uploads
- name: Resilience Testing
  tags:
  - Actions
  - Action Templates
  - Chaos Components
  - Chaos Hubs
  - ChaosGuard Conditions
  - ChaosGuard Rules
  - DR Tests
  - Experiments
  - Experiment Templates
  - Faults
  - Fault Templates
  - Chaos Infrastructure
  - Health
  - Network Maps
  - Onboarding
  - Probes
  - Probe Templates
  - Chaos Recommendations
  - Risks
