openapi: 3.2.0
info:
  title: Harness Workspace Templates API
  version: '1.0'
  description: The Harness Software Delivery Platform uses OpenAPI Specification v3.0.
  contact:
    name: API Support
    email: contact@harness.io
    url: https://harness.io/
  x-logo:
    url: https://mma.prnewswire.com/media/779232/Harnes_logo_horizontal.jpg?p=facebook
    altText: Harness
  termsOfService: https://harness.io/terms-of-use/
servers:
- url: https://app.harness.io
  description: Harness host URL
- url: https://{vanity}
  description: Vanity URL
  variables:
    vanity:
      default: app.harness.io
security:
- x-api-key: []
tags:
- name: workspace_templates
  description: Workspace Templates Service handles the API for managing template associations with workspaces.
paths:
  /iacm/api/orgs/{org}/projects/{project}/workspace/template/{workspace_id}/yaml-diff:
    get:
      tags:
      - workspace_templates
      summary: Retrieve workspace-template reconciliation diff
      description: Get the differences between the current workspace YAML and what it will look like when reconciled with the template
      operationId: workspace_templates#get-workspace-template-reconciliation-diff
      parameters:
      - name: org
        in: path
        description: Org is the organisation identifier.
        required: true
        schema:
          type: string
          description: Org is the organisation identifier.
          example: f
          minLength: 1
          maxLength: 128
        example: c
      - name: project
        in: path
        description: Project is the project identifier.
        required: true
        schema:
          type: string
          description: Project is the project identifier.
          example: d
          minLength: 1
          maxLength: 128
        example: m
      - name: workspace_id
        in: path
        description: Workspace identifier
        required: true
        schema:
          type: string
          description: Workspace identifier
          example: e
          minLength: 1
          maxLength: 128
        example: 0fh
      - name: Harness-Account
        in: header
        description: Account is the internal customer account ID.
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Account is the internal customer account ID.
          example: 9t
          minLength: 1
          maxLength: 128
        example: 29s
      responses:
        '200':
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetWorkspaceTemplateReconciliationDiffResponse'
              example:
                currentWorkspaceYaml: Id quibusdam mollitia qui.
                reconcilableWorkspaceYaml: Id ipsam delectus sit.
                requiresReconciliation: true
        '400':
          description: 'BadRequestError: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '401':
          description: 'UnauthorizedError: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '403':
          description: 'ForbiddenError: Forbidden response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '404':
          description: 'NotFoundError: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '408':
          description: 'TimeoutError: Request Timeout response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '409':
          description: 'ConflictError: Conflict response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '423':
          description: 'LockedError: Locked response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '499':
          description: 'ContextCancelledError:  response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '500':
          description: 'InternalServerError: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '502':
          description: 'BadGatewayError: Bad Gateway response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
  /iacm/api/orgs/{org}/projects/{project}/workspace/templates:
    post:
      tags:
      - workspace_templates
      summary: Create workspace template
      description: Add a workspace-template combination to the table.
      operationId: workspace_templates#add-workspace-template
      parameters:
      - name: org
        in: path
        description: Org is the organisation identifier.
        required: true
        schema:
          type: string
          description: Org is the organisation identifier.
          example: 7fl
          minLength: 1
          maxLength: 128
        example: tp
      - name: project
        in: path
        description: Project is the project identifier.
        required: true
        schema:
          type: string
          description: Project is the project identifier.
          example: g2
          minLength: 1
          maxLength: 128
        example: g
      - name: Harness-Account
        in: header
        description: Account is the internal customer account ID.
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Account is the internal customer account ID.
          example: dv
          minLength: 1
          maxLength: 128
        example: qs
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWorkspaceTemplateRequest'
            example:
              template_id: ah
              version: '64'
              workspace_id: l2u
      responses:
        '201':
          description: Created response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateWorkspaceTemplateResponse'
              example:
                account: kp4
                created_at: 1627590400
                org: nfz
                project: rt
                template_id: gk
                updated_at: 1627686800
                version: l
                workspace_id: z
        '400':
          description: 'BadRequestError: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '401':
          description: 'UnauthorizedError: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '403':
          description: 'ForbiddenError: Forbidden response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '404':
          description: 'NotFoundError: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '408':
          description: 'TimeoutError: Request Timeout response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '409':
          description: 'ConflictError: Conflict response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '423':
          description: 'LockedError: Locked response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '499':
          description: 'ContextCancelledError:  response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '500':
          description: 'InternalServerError: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '502':
          description: 'BadGatewayError: Bad Gateway response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
  /iacm/api/orgs/{org}/projects/{project}/workspace/templates/{template_id}:
    get:
      tags:
      - workspace_templates
      summary: List workspaces by template id
      description: Get all workspaces associated with a specific template ID for a given scope.
      operationId: workspace_templates#get-workspaces-by-template-id
      parameters:
      - name: org
        in: path
        description: Org is the organisation identifier.
        required: true
        schema:
          type: string
          description: Org is the organisation identifier.
          example: w5a
          minLength: 1
          maxLength: 128
        example: z
      - name: project
        in: path
        description: Project is the project identifier.
        required: true
        schema:
          type: string
          description: Project is the project identifier.
          example: a
          minLength: 1
          maxLength: 128
        example: '7'
      - name: template_id
        in: path
        description: Template identifier to filter workspaces
        required: true
        schema:
          type: string
          description: Template identifier to filter workspaces
          example: kzp
          minLength: 1
          maxLength: 128
        example: x6u
      - name: Harness-Account
        in: header
        description: Account is the internal customer account ID.
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Account is the internal customer account ID.
          example: un
          minLength: 1
          maxLength: 128
        example: f
      responses:
        '200':
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HarnessIacmWorkspaceTemplate'
                description: List of workspaces associated with the template ID
                example:
                - account: o9n
                  created_at: 1627590400
                  org: x96
                  project: 8jn
                  template_id: w8
                  updated_at: 1627686800
                  version: de
                  workspace_id: wx
                - account: o9n
                  created_at: 1627590400
                  org: x96
                  project: 8jn
                  template_id: w8
                  updated_at: 1627686800
                  version: de
                  workspace_id: wx
                - account: o9n
                  created_at: 1627590400
                  org: x96
                  project: 8jn
                  template_id: w8
                  updated_at: 1627686800
                  version: de
                  workspace_id: wx
              example:
              - account: o9n
                created_at: 1627590400
                org: x96
                project: 8jn
                template_id: w8
                updated_at: 1627686800
                version: de
                workspace_id: wx
              - account: o9n
                created_at: 1627590400
                org: x96
                project: 8jn
                template_id: w8
                updated_at: 1627686800
                version: de
                workspace_id: wx
        '400':
          description: 'BadRequestError: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '401':
          description: 'UnauthorizedError: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '403':
          description: 'ForbiddenError: Forbidden response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '404':
          description: 'NotFoundError: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '408':
          description: 'TimeoutError: Request Timeout response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '409':
          description: 'ConflictError: Conflict response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '423':
          description: 'LockedError: Locked response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '499':
          description: 'ContextCancelledError:  response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '500':
          description: 'InternalServerError: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '502':
          description: 'BadGatewayError: Bad Gateway response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
  /iacm/api/orgs/{org}/projects/{project}/workspace/templates/{template_id}/{workspace_id}:
    delete:
      tags:
      - workspace_templates
      summary: Delete workspace template
      description: Remove the association between a template and a workspace.
      operationId: workspace_templates#remove-workspace-template
      parameters:
      - name: org
        in: path
        description: Org is the organisation identifier.
        required: true
        schema:
          type: string
          description: Org is the organisation identifier.
          example: 3w
          minLength: 1
          maxLength: 128
        example: w5
      - name: project
        in: path
        description: Project is the project identifier.
        required: true
        schema:
          type: string
          description: Project is the project identifier.
          example: sf4
          minLength: 1
          maxLength: 128
        example: ovs
      - name: template_id
        in: path
        description: Template identifier
        required: true
        schema:
          type: string
          description: Template identifier
          example: ik
          minLength: 1
          maxLength: 128
        example: ze
      - name: workspace_id
        in: path
        description: Workspace identifier
        required: true
        schema:
          type: string
          description: Workspace identifier
          example: vh
          minLength: 1
          maxLength: 128
        example: klh
      - name: Harness-Account
        in: header
        description: Account is the internal customer account ID.
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Account is the internal customer account ID.
          example: dfh
          minLength: 1
          maxLength: 128
        example: 5h
      responses:
        '204':
          description: No Content response.
        '400':
          description: 'BadRequestError: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '401':
          description: 'UnauthorizedError: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '403':
          description: 'ForbiddenError: Forbidden response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '404':
          description: 'NotFoundError: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '408':
          description: 'TimeoutError: Request Timeout response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '409':
          description: 'ConflictError: Conflict response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '423':
          description: 'LockedError: Locked response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '499':
          description: 'ContextCancelledError:  response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '500':
          description: 'InternalServerError: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '502':
          description: 'BadGatewayError: Bad Gateway response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
    put:
      tags:
      - workspace_templates
      summary: Update workspace template
      description: Update a workspace template combo to change its version.
      operationId: workspace_templates#update-workspace-template
      parameters:
      - name: org
        in: path
        description: Org is the organisation identifier.
        required: true
        schema:
          type: string
          description: Org is the organisation identifier.
          example: q
          minLength: 1
          maxLength: 128
        example: y
      - name: project
        in: path
        description: Project is the project identifier.
        required: true
        schema:
          type: string
          description: Project is the project identifier.
          example: vtk
          minLength: 1
          maxLength: 128
        example: l0
      - name: template_id
        in: path
        description: Template identifier
        required: true
        schema:
          type: string
          description: Template identifier
          example: jo
          minLength: 1
          maxLength: 128
        example: 3pd
      - name: workspace_id
        in: path
        description: Workspace identifier
        required: true
        schema:
          type: string
          description: Workspace identifier
          example: 84d
          minLength: 1
          maxLength: 128
        example: '1'
      - name: Harness-Account
        in: header
        description: Account is the internal customer account ID.
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Account is the internal customer account ID.
          example: x
          minLength: 1
          maxLength: 128
        example: l
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWorkspaceTemplateRequest'
            example:
              version: he
      responses:
        '200':
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateWorkspaceTemplateResponse'
              example:
                account: 14y
                created_at: 1627590400
                org: 0l
                project: h5a
                template_id: n
                updated_at: 1627686800
                version: fx
                workspace_id: '8'
        '400':
          description: 'BadRequestError: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '401':
          description: 'UnauthorizedError: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '403':
          description: 'ForbiddenError: Forbidden response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '404':
          description: 'NotFoundError: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '408':
          description: 'TimeoutError: Request Timeout response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '409':
          description: 'ConflictError: Conflict response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '423':
          description: 'LockedError: Locked response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '499':
          description: 'ContextCancelledError:  response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '500':
          description: 'InternalServerError: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
        '502':
          description: 'BadGatewayError: Bad Gateway response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/IaCMError'
components:
  schemas:
    CreateWorkspaceTemplateResponse:
      type: object
      properties:
        account:
          type: string
          description: Account identifier.
          example: we
          minLength: 1
          maxLength: 128
        created_at:
          type: integer
          description: Timestamp when the workspace-template association was created.
          example: 1627590400
          format: int64
        org:
          type: string
          description: Organization identifier.
          example: 3ox
          minLength: 1
          maxLength: 128
        project:
          type: string
          description: Project identifier.
          example: ssv
          minLength: 1
          maxLength: 128
        template_id:
          type: string
          description: Template identifier.
          example: 5bn
          minLength: 1
          maxLength: 128
        updated_at:
          type: integer
          description: Timestamp when the workspace-template association was last updated.
          example: 1627686800
          format: int64
        version:
          type: string
          description: Template version associated with the workspace.
          example: l
          minLength: 1
          maxLength: 32
        workspace_id:
          type: string
          description: Workspace identifier.
          example: rw
          minLength: 1
          maxLength: 128
      example:
        account: '7'
        created_at: 1627590400
        org: 9eu
        project: zhn
        template_id: n9
        updated_at: 1627686800
        version: qsx
        workspace_id: c8a
      required:
      - workspace_id
      - template_id
      - created_at
      - updated_at
      - account
      - project
      - org
    CreateWorkspaceTemplateRequest:
      type: object
      properties:
        template_id:
          type: string
          description: Template identifier
          example: 8k
          minLength: 1
          maxLength: 128
        version:
          type: string
          description: Template version
          example: hw
          minLength: 1
          maxLength: 64
        workspace_id:
          type: string
          description: Workspace identifier
          example: k
          minLength: 1
          maxLength: 128
      example:
        template_id: 5n
        version: zw
        workspace_id: vra
      required:
      - workspace_id
      - template_id
      - version
    GetWorkspaceTemplateReconciliationDiffResponse:
      type: object
      properties:
        currentWorkspaceYaml:
          type: string
          description: Current workspace YAML
          example: Maiores omnis est pariatur ipsam veniam molestias.
        reconcilableWorkspaceYaml:
          type: string
          description: Workspace YAML after applying changes from the template
          example: Et eum.
        requiresReconciliation:
          type: boolean
          description: Indicates if the workspace needs template-based reconciliation
          example: true
      example:
        currentWorkspaceYaml: Ea totam dolorem in.
        reconcilableWorkspaceYaml: Rerum ad ducimus consectetur.
        requiresReconciliation: true
      required:
      - currentWorkspaceYaml
      - reconcilableWorkspaceYaml
      - requiresReconciliation
    HarnessIacmWorkspaceTemplate:
      type: object
      properties:
        account:
          type: string
          description: Account identifier.
          example: 9ea
          minLength: 1
          maxLength: 128
        created_at:
          type: integer
          description: Timestamp when the workspace-template association was created.
          example: 1627590400
          format: int64
        org:
          type: string
          description: Organization identifier.
          example: lgs
          minLength: 1
          maxLength: 128
        project:
          type: string
          description: Project identifier.
          example: h1
          minLength: 1
          maxLength: 128
        template_id:
          type: string
          description: Template identifier.
          example: fyc
          minLength: 1
          maxLength: 128
        updated_at:
          type: integer
          description: Timestamp when the workspace-template association was last updated.
          example: 1627686800
          format: int64
        version:
          type: string
          description: Template version associated with the workspace.
          example: n
          minLength: 1
          maxLength: 32
        workspace_id:
          type: string
          description: Workspace identifier.
          example: 4k
          minLength: 1
          maxLength: 128
      description: WorkspaceTemplateResource is the representation for a workspace-template association.
      example:
        account: '2'
        created_at: 1627590400
        org: hg
        project: jql
        template_id: '3'
        updated_at: 1627686800
        version: u
        workspace_id: '8'
      required:
      - workspace_id
      - template_id
      - created_at
      - updated_at
      - account
      - project
      - org
    IaCMError:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: false
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      example:
        fault: false
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: false
        timeout: true
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    UpdateWorkspaceTemplateRequest:
      type: object
      properties:
        version:
          type: string
          description: New template version
          example: zgo
          minLength: 1
          maxLength: 64
      example:
        version: o
      required:
      - version
    UpdateWorkspaceTemplateResponse:
      type: object
      properties:
        account:
          type: string
          description: Account identifier.
          example: mq
          minLength: 1
          maxLength: 128
        created_at:
          type: integer
          description: Timestamp when the workspace-template association was created.
          example: 1627590400
          format: int64
        org:
          type: string
          description: Organization identifier.
          example: '6'
          minLength: 1
          maxLength: 128
        project:
          type: string
          description: Project identifier.
          example: k
          minLength: 1
          maxLength: 128
        template_id:
          type: string
          description: Template identifier.
          example: a7z
          minLength: 1
          maxLength: 128
        updated_at:
          type: integer
          description: Timestamp when the workspace-template association was last updated.
          example: 1627686800
          format: int64
        version:
          type: string
          description: Template version associated with the workspace.
          example: lj
          minLength: 1
          maxLength: 32
        workspace_id:
          type: string
          description: Workspace identifier.
          example: o
          minLength: 1
          maxLength: 128
      example:
        account: zs
        created_at: 1627590400
        org: wt0
        project: 5tu
        template_id: y
        updated_at: 1627686800
        version: vq
        workspace_id: d
      required:
      - workspace_id
      - template_id
      - created_at
      - updated_at
      - account
      - project
      - org
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
      description: API key is a token provided while making the API calls. This is used to authenticate the client at the exposed endpoint.
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
x-stoplight:
  id: oc91t4vrfnjyi
x-tagGroups:
- name: Organizations
  tags:
  - Organization
- name: Projects
  tags:
  - Org Project
  - Project
- name: Secrets
  tags:
  - Account Secret
  - Org Secret
  - Project Secret
  - Secrets
- name: Connectors
  tags:
  - Account Connector
  - Org Connector
  - Project Connector
  - Connectors
  - GoogleSecretManagerConnector
- name: Roles
  tags:
  - Account Roles
  - Organization Roles
  - Project Roles
  - Roles
- name: Resource Groups
  tags:
  - Account Resource Groups
  - Organization Resource Groups
  - Project Resource Groups
  - Filter Resource Groups
  - Harness Resource Group
  - Zendesk
- name: Role Assignments
  tags:
  - Account Role Assignments
  - Org Role Assignments
  - Project Role Assignments
  - Role Assignments
- name: Platform
  tags:
  - Access Control List
  - Account Banner
  - Account Banner
  - Account Licensed Modules
  - Account License Type
  - Account Webhooks
  - AccountSetting
  - Accounts
  - Analyze Account Access Policy
  - Analyze Organization Access Policy
  - Analyze Project Access Policy
  - ApiKey
  - Audit
  - AuditFilters
  - Authentication Settings
  - Canny
  - Devops Essentials License Data By Account
  - EULA
  - Filter
  - Harness Resource Type
  - Invite
  - IP Allowlist
  - Nextgen Ldap
  - Notification Channels
  - Notification Rules
  - OIDC
  - Oidc-Access-Token
  - Oidc-ID-Token
  - Org Webhooks
  - Permissions
  - Project Webhooks
  - Secret Managers
  - Service Account
  - Setting
  - SMTP
  - Source Code Manager
  - Token
  - User
  - User Group
  - Variables
- name: Delegate
  tags:
  - Agent mTLS Endpoint Management
  - Delegate Download Resource
  - Delegate Group Tags Resource
  - Delegate Setup Resource
  - Delegate Token Resource
- name: Pipelines
  tags:
  - Pipelines
  - Input Sets
  - Approvals
  - Pipeline Execution
  - Pipeline Dashboard
  - Pipeline Input Set
  - Pipeline
  - Pipeline Execution Details
  - Pipeline Execute
  - Pipeline Refresh
  - Pipeline data retention
  - Triggers
  - TriggersEvents
  - Webhook Triggers
  - Webhook Event Handler
  - DryRunPipeline
- name: Artifact Registry
  tags:
  - Registries
  - Artifacts
  - Docker Artifacts
  - Helm Artifacts
  - quarantine
  - Webhooks
  - Spaces
  - Replication
  - Registry V3 - Registries
  - Registry V3 - Packages
  - Registry V3 - Versions
  - Registry V3 - Files
  - Registry V3 - Metadata
  - Registry V3 - Firewall
  - Registry V3 - Transfer
- name: Database DevOps
  tags:
  - Database Schema
  - Database Instance
  - Deployed State
  - Execution Config
  - Migration State
- name: CD
  tags:
  - K8s Release Service Mapping
  - CustomDeployment
  - Environments
  - EnvironmentGroup
  - Infrastructures
  - Usage
  - File Store
  - Service Dashboard
  - ServiceOverrides
  - Rollback
  - tas
- name: Deployment Freeze
  tags:
  - Freeze CRUD
  - Freeze Evaluation
  - Freeze Schema
- name: Services
  tags:
  - Account Services
  - Org Services
  - Project Services
  - Services
- name: Rancher Infrastructures
  tags:
  - Account Rancher Infrastructure
  - Org Rancher Infrastructure
  - Project Rancher Infrastructure
- name: Templates
  tags:
  - Account Template
  - Org Template
  - Project Template
  - Templates
  - Global Templates
- name: GitOps
  tags:
  - Agents
  - Application
  - Applications
  - Certificates
  - Clusters
  - Dashboard Aggregates
  - Dashboards
  - GnuPGP Keys
  - GPG Keys
  - Hosts
  - Project mappings
  - Projects
  - Reconciler
  - Repositories
  - Repository Certificates
  - Repository credentials
  - ValidateHost
- name: GitX
  tags:
  - GitX Webhooks
  - Org Gitx Webhooks
  - Project Gitx Webhooks
- name: CACM
  tags:
  - Anomalies Ignorelist Rule
  - Anomalies
  - BI Dashboards
  - Budgets
  - Budget Groups
  - Cost Categories
  - Cloud Accounts
  - K8S Connectors Metadata
  - Notification Settings v2
  - Overview
  - Data Job Status
  - Recommendation cost settings
  - Unit Metric
  - Anomaly Comments
  - Cloud and AI cost anomaly details
  - Cloud and AI cost anomalies v2
  - Cost Details
  - Currency Preferences
  - External Data Provider
  - AiEngine
  - CACM governance cost settings
  - Governance Enforcement Recommendation APIs
  - Governance Alert
  - Governance Overview
  - Governance Recommendation APIs
  - RuleEnforcement
  - Rule Executions
  - Rule
  - Rule Sets
  - Perspectives Folders
  - Perspective Reports
  - Perspectives
  - Cost Category Jira Project Mapping
  - Recommendations Details
  - Recommendations
  - Recommendation Jira
  - Recommendation Preferences
  - Recommendation Presets
  - Recommendation Servicenow
  - Recommendation Tags
  - Recommendation Ignore List
  - AutoStopping Rules
  - AutoStopping Rules V2
  - AutoStopping Load Balancers
  - AutoStopping Fixed Schedules
  - AutoStopping Alerts
  - Commitment Orchestrator Events APIs
- name: Feature Flags
  tags:
  - API Keys
  - Feature Flags
  - Targets
  - Target Groups
  - Environment Perspectives
  - Anomalies
  - Proxy
  - Tags
- name: SRM
  tags:
  - Monitored Services
  - SLOs dashboard
  - NG SLOs
  - SLOs
  - Downtime
  - Srm Notification
- name: Internal Developer Portal - IDP
  tags:
  - Entities
  - Teams
  - CatalogCustomProperties
  - Scores
  - DataSource
  - KubernetesDataPoints
  - AggregationRules
  - AppConfig
  - PluginInfo
  - LayoutProxy
  - Kinds
  - LayoutsV3
  - LayoutsV4
- name: Environment Management - IDP
  tags:
  - Environment
  - Infrastructure
  - Instance
- name: Custom Dashboards
  tags:
  - aida
  - dashboards
  - downloads
  - embed
  - folders
- name: Policy Management
  tags:
  - dashboard
  - examples
  - policies
  - evaluate
  - evaluations
  - policysets
  - system
- name: Code
  tags:
  - repository
  - status_checks
  - pullreq
  - upload
  - webhook
  - resource
  - rules
  - labels
- name: IaCM
  tags:
  - usage
  - approvals
  - costs
  - executions
  - module-registry
  - workspaces
  - settings
  - tf-standard-backend
  - variables
- name: STO
  tags:
  - Exemptions
  - Issues
  - Scans
  - Products
  - Test Targets
  - Target Variants
- name: SEI
  tags:
  - Collection categories
  - Collections
  - Contributors
  - DORA
- name: Git Sync (deprecated)
  tags:
  - Git Branches
  - Git Full Sync
  - Git Sync Settings
  - Git Sync
  - Git Sync Errors
- name: Error Models
  tags:
  - Error Response
  - Governance Metadata
- name: Supply Chain Security
  tags:
  - integration
  - PipelineInfraConfig
  - SBOM
  - Integration Step Config
  - Delete Step Config
  - Delete Repositories
  - Pipeline Store Config
  - Evidence Vault [Beta]
- name: Release Management
  tags:
  - Release Groups
  - Releases
  - Orchestration Processes
  - Orchestration Activities
  - Orchestration Executions
  - Conflicts
  - Freeze
  - Reports
  - Uploads
- name: Resilience Testing
  tags:
  - Actions
  - Action Templates
  - Chaos Components
  - Chaos Hubs
  - ChaosGuard Conditions
  - ChaosGuard Rules
  - DR Tests
  - Experiments
  - Experiment Templates
  - Faults
  - Fault Templates
  - Chaos Infrastructure
  - Health
  - Network Maps
  - Onboarding
  - Probes
  - Probe Templates
  - Chaos Recommendations
  - Risks
