openapi: 3.2.0
info:
  title: Harness Org Project API
  version: '1.0'
  description: The Harness Software Delivery Platform uses OpenAPI Specification v3.0.
  contact:
    name: API Support
    email: contact@harness.io
    url: https://harness.io/
  x-logo:
    url: https://mma.prnewswire.com/media/779232/Harnes_logo_horizontal.jpg?p=facebook
    altText: Harness
  termsOfService: https://harness.io/terms-of-use/
servers:
- url: https://app.harness.io
  description: Harness host URL
- url: https://{vanity}
  description: Vanity URL
  variables:
    vanity:
      default: app.harness.io
security:
- x-api-key: []
tags:
- name: Org Project
  description: This contains APIs for projects.
  x-displayName: Project [Beta]
paths:
  /v1/orgs/{org}/projects:
    parameters:
    - $ref: '#/components/parameters/OrgPathParam'
    post:
      summary: Create a project
      responses:
        '201':
          $ref: '#/components/responses/ProjectResponse'
      operationId: create-org-scoped-project
      security:
      - x-api-key: []
      description: Creates a new project
      requestBody:
        $ref: '#/components/requestBodies/CreateProjectRequest'
      parameters:
      - $ref: '#/components/parameters/AccountHeader'
      tags:
      - Org Project
    get:
      summary: List projects
      responses:
        '200':
          $ref: '#/components/responses/ProjectListResponse'
      operationId: get-org-scoped-projects
      description: Retrieves the information of the projects.
      security:
      - x-api-key: []
      parameters:
      - $ref: '#/components/parameters/ProjectsQueryParam'
      - schema:
          type: boolean
          default: true
        in: query
        name: has_module
        description: This boolean specifies whether to filter projects which has the module of type passed in the moduleType parameter or not
      - schema:
          type: string
        in: query
        name: module_type
        description: Project's module type
      - $ref: '#/components/parameters/onlyFavorites'
      - $ref: '#/components/parameters/SearchTerm1'
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/Limit1'
      - $ref: '#/components/parameters/AccountHeader'
      - $ref: '#/components/parameters/Sort1'
      - $ref: '#/components/parameters/Order'
      tags:
      - Org Project
  /v1/orgs/{org}/projects/{project}:
    parameters:
    - $ref: '#/components/parameters/OrgPathParam'
    - $ref: '#/components/parameters/ProjectPathParam'
    get:
      summary: Retrieve a project
      responses:
        '200':
          $ref: '#/components/responses/ProjectResponse'
      operationId: get-org-scoped-project
      description: Retrieves the information of the project with the matching project identifier.
      security:
      - x-api-key: []
      parameters:
      - $ref: '#/components/parameters/AccountHeader'
      tags:
      - Org Project
    put:
      summary: Update a project
      responses:
        '200':
          $ref: '#/components/responses/ProjectResponse'
      operationId: update-org-scoped-project
      description: Updates the information of the project with the matching project identifier.
      security:
      - x-api-key: []
      requestBody:
        $ref: '#/components/requestBodies/UpdateProjectRequest'
      parameters:
      - $ref: '#/components/parameters/AccountHeader'
      tags:
      - Org Project
    delete:
      summary: Delete a project
      responses:
        '200':
          $ref: '#/components/responses/ProjectResponse'
      operationId: delete-org-scoped-project
      description: Deletes the information of the project with the matching project identifier.
      security:
      - x-api-key: []
      parameters:
      - $ref: '#/components/parameters/AccountHeader'
      tags:
      - Org Project
components:
  parameters:
    onlyFavorites:
      name: only_favorites
      in: query
      required: false
      schema:
        type: boolean
      description: Enable this field to fetch only the entities that are marked as favorites.
    SearchTerm1:
      name: search_term
      in: query
      required: false
      schema:
        type: string
      description: This would be used to filter resources having attributes matching with search term.
    ProjectsQueryParam:
      name: project
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
      description: Identifier field of the projects the resource is scoped to
    ProjectPathParam:
      name: project
      in: path
      required: true
      schema:
        type: string
      description: Identifier field of the project the resource is scoped to
    Sort1:
      name: sort
      in: query
      required: false
      schema:
        type: string
        enum:
        - name
        - identifier
        - created
        - updated
      description: Parameter on the basis of which sorting is done.
    OrgPathParam:
      name: org
      in: path
      required: true
      schema:
        type: string
      description: Identifier field of the organization the resource is scoped to
    AccountHeader:
      name: Harness-Account
      in: header
      required: false
      schema:
        type: string
      description: Identifier field of the account the resource is scoped to. This is required for Authorization methods other than the x-api-key header. If you are using the x-api-key header, this can be skipped.
    Order:
      name: order
      in: query
      required: false
      schema:
        type: string
        enum:
        - ASC
        - DESC
      description: Order on the basis of which sorting is done.
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        default: 0
      description: "Pagination page number strategy: Specify the page number within the paginated collection related to the number of items in each page\t"
    Limit1:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 20
        maximum: 1000
      description: Number of items to return per page.
  requestBodies:
    CreateProjectRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CreateProjectRequest'
          examples:
            example-create-project-request-json:
              value:
                project:
                  identifier: example_project_identifier
                  name: example-project-name
                  color: '#0063F7'
                  modules:
                  - CD
                  description: This is a example project
                  tags:
                    property1: value1
                    property2: value2
        application/yaml:
          schema:
            $ref: '#/components/schemas/CreateProjectRequest'
          examples:
            example-create-project-request-yaml:
              value: "project:\n  identifier: example_project_identifier\n  name: example-project-name\n  color: '#0063F7'\n  modules:\n    - CD\n  description: This is a example project\n  tags:\n    property1: value1\n    property2: value2\n"
      description: Post the necessary fields for the API to create a project.
      required: true
    UpdateProjectRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UpdateProjectRequest'
          examples:
            example-project-update-request-json:
              value:
                project:
                  identifier: example_project_identifier
                  name: example-project-name
                  color: '#0063F7'
                  modules:
                  - CD
                  description: This is a example project
                  tags:
                    property1: value1
                    property2: value2
        application/yaml:
          schema:
            $ref: '#/components/schemas/UpdateProjectRequest'
          examples:
            example-project-update-request-yaml:
              value: "project:\n  identifier: example_project_identifier\n  name: example-project-name\n  color: '#0063F7'\n  modules:\n    - CD\n  description: This is a example project\n  tags:\n    property1: value1\n    property2: value2\n"
      description: Put the necessary fields for the API to update a Project.
      required: true
  responses:
    ProjectListResponse:
      description: Project list response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ProjectResponse'
          examples:
            example-project-list-response-json:
              value:
              - project:
                  org: example_org_identifier
                  identifier: example_project_identifier
                  name: example-project-name
                  color: '#0063F7'
                  modules:
                  - CD
                  description: This is a example project
                  tags:
                    property1: value1
                    property2: value2
                created: 1234567890
                updated: 1234567890
                isFavorite: true
        application/yaml:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ProjectResponse'
          examples:
            example-project-list-response-yaml:
              value: "- project:\n    org: example_org_identifier\n    identifier: example_project_identifier\n    name: example-project-name\n    color: '#0063F7'\n    modules:\n      - CD\n    description: This is a example project\n    tags:\n      property1: value1\n      property2: value2\n  created: 1234567890\n  updated: 1234567890\n  isFavorite: true\n"
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
    ProjectResponse:
      description: Project response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProjectResponse'
          examples:
            example-project-response-json:
              value:
                project:
                  org: example_org_identifier
                  identifier: example_project_identifier
                  name: example-project-name
                  color: '#0063F7'
                  modules:
                  - CD
                  description: This is a example project
                  tags:
                    property1: value1
                    property2: value2
                created: 1234567890
                updated: 1234567890
                isFavorite: true
        application/yaml:
          schema:
            $ref: '#/components/schemas/ProjectResponse'
          examples:
            example-project-response-yaml:
              value: "project:\n  org: example_org_identifier\n  identifier: example_project_identifier\n  name: example-project-name\n  color: '#0063F7'\n  modules:\n    - CD\n  description: This is a example project\n  tags:\n    property1: value1\n    property2: value2\ncreated: 1234567890\nupdated: 1234567890\nisFavorite: true\n"
  schemas:
    ModuleType:
      type: string
      description: Type of Modules
      enum:
      - CD
      - CI
      - CV
      - CF
      - CE
      - STO
      - CORE
      - PMS
      - TEMPLATESERVICE
      - GOVERNANCE
      - CHAOS
      - CET
      - IDP
      - SSCA
      - SEI
      - CODE
      - HAR
    CreateProjectRequest:
      description: Create project request
      type: object
      properties:
        project:
          $ref: '#/components/schemas/ProjectRequest'
      required:
      - project
    ProjectRequest:
      description: Project model
      type: object
      x-examples:
        example-1:
          identifier: example_project_identifier
          name: example-project-name
          color: '#0063F7'
          modules:
          - CD
          description: This is a example project
          tags:
            property1: value1
            property2: value2
      properties:
        identifier:
          type: string
          minLength: 1
          pattern: ^[a-zA-Z_][0-9a-zA-Z_$]{0,127}$
          description: Project identifier
          maxLength: 128
        name:
          type: string
          minLength: 1
          pattern: ^[a-zA-Z_][0-9a-zA-Z-_ ]{0,127}$
          description: Project name
          maxLength: 128
        color:
          type: string
          description: Project color
        modules:
          type: array
          maxItems: 1024
          description: List of modules for project
          items:
            $ref: '#/components/schemas/ModuleType'
        description:
          type: string
          maxLength: 1024
          description: Project description
        tags:
          type: object
          additionalProperties:
            type: string
          maxProperties: 128
          description: Project tags
      required:
      - identifier
      - name
    ProjectResponse:
      description: Project response model
      type: object
      properties:
        project:
          $ref: '#/components/schemas/Project'
        created:
          type: integer
          format: int64
          description: Creation timestamp for the project
        updated:
          type: integer
          format: int64
          description: Updated timestamp for the project
        isFavorite:
          type: boolean
          description: True if its your favorite project
    UpdateProjectRequest:
      description: Update project request
      type: object
      properties:
        project:
          $ref: '#/components/schemas/ProjectRequest'
      required:
      - project
    Project:
      description: Project model
      type: object
      x-examples:
        example-1:
          identifier: example_project_identifier
          name: example-project-name
          org: example_org_identifier
          color: '#0063F7'
          modules:
          - CD
          description: This is a example project
          tags:
            property1: value1
            property2: value2
      properties:
        identifier:
          type: string
          minLength: 1
          pattern: ^[a-zA-Z_][0-9a-zA-Z_$]{0,127}$
          description: Project identifier
          maxLength: 128
        name:
          type: string
          minLength: 1
          pattern: ^[a-zA-Z_][0-9a-zA-Z-_ ]{0,127}$
          description: Project name
          maxLength: 128
        org:
          type: string
          description: Organization identifier for the project
        color:
          type: string
          description: Project color
        modules:
          type: array
          maxItems: 1024
          description: List of modules for project
          items:
            $ref: '#/components/schemas/ModuleType'
        description:
          type: string
          maxLength: 1024
          description: Project description
        tags:
          type: object
          additionalProperties:
            type: string
          maxProperties: 128
          description: Project tags
      required:
      - identifier
      - name
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
      description: API key is a token provided while making the API calls. This is used to authenticate the client at the exposed endpoint.
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
x-stoplight:
  id: oc91t4vrfnjyi
x-tagGroups:
- name: Organizations
  tags:
  - Organization
- name: Projects
  tags:
  - Org Project
  - Project
- name: Secrets
  tags:
  - Account Secret
  - Org Secret
  - Project Secret
  - Secrets
- name: Connectors
  tags:
  - Account Connector
  - Org Connector
  - Project Connector
  - Connectors
  - GoogleSecretManagerConnector
- name: Roles
  tags:
  - Account Roles
  - Organization Roles
  - Project Roles
  - Roles
- name: Resource Groups
  tags:
  - Account Resource Groups
  - Organization Resource Groups
  - Project Resource Groups
  - Filter Resource Groups
  - Harness Resource Group
  - Zendesk
- name: Role Assignments
  tags:
  - Account Role Assignments
  - Org Role Assignments
  - Project Role Assignments
  - Role Assignments
- name: Platform
  tags:
  - Access Control List
  - Account Banner
  - Account Banner
  - Account Licensed Modules
  - Account License Type
  - Account Webhooks
  - AccountSetting
  - Accounts
  - Analyze Account Access Policy
  - Analyze Organization Access Policy
  - Analyze Project Access Policy
  - ApiKey
  - Audit
  - AuditFilters
  - Authentication Settings
  - Canny
  - Devops Essentials License Data By Account
  - EULA
  - Filter
  - Harness Resource Type
  - Invite
  - IP Allowlist
  - Nextgen Ldap
  - Notification Channels
  - Notification Rules
  - OIDC
  - Oidc-Access-Token
  - Oidc-ID-Token
  - Org Webhooks
  - Permissions
  - Project Webhooks
  - Secret Managers
  - Service Account
  - Setting
  - SMTP
  - Source Code Manager
  - Token
  - User
  - User Group
  - Variables
- name: Delegate
  tags:
  - Agent mTLS Endpoint Management
  - Delegate Download Resource
  - Delegate Group Tags Resource
  - Delegate Setup Resource
  - Delegate Token Resource
- name: Pipelines
  tags:
  - Pipelines
  - Input Sets
  - Approvals
  - Pipeline Execution
  - Pipeline Dashboard
  - Pipeline Input Set
  - Pipeline
  - Pipeline Execution Details
  - Pipeline Execute
  - Pipeline Refresh
  - Pipeline data retention
  - Triggers
  - TriggersEvents
  - Webhook Triggers
  - Webhook Event Handler
  - DryRunPipeline
- name: Artifact Registry
  tags:
  - Registries
  - Artifacts
  - Docker Artifacts
  - Helm Artifacts
  - quarantine
  - Webhooks
  - Spaces
  - Replication
  - Registry V3 - Registries
  - Registry V3 - Packages
  - Registry V3 - Versions
  - Registry V3 - Files
  - Registry V3 - Metadata
  - Registry V3 - Firewall
  - Registry V3 - Transfer
- name: Database DevOps
  tags:
  - Database Schema
  - Database Instance
  - Deployed State
  - Execution Config
  - Migration State
- name: CD
  tags:
  - K8s Release Service Mapping
  - CustomDeployment
  - Environments
  - EnvironmentGroup
  - Infrastructures
  - Usage
  - File Store
  - Service Dashboard
  - ServiceOverrides
  - Rollback
  - tas
- name: Deployment Freeze
  tags:
  - Freeze CRUD
  - Freeze Evaluation
  - Freeze Schema
- name: Services
  tags:
  - Account Services
  - Org Services
  - Project Services
  - Services
- name: Rancher Infrastructures
  tags:
  - Account Rancher Infrastructure
  - Org Rancher Infrastructure
  - Project Rancher Infrastructure
- name: Templates
  tags:
  - Account Template
  - Org Template
  - Project Template
  - Templates
  - Global Templates
- name: GitOps
  tags:
  - Agents
  - Application
  - Applications
  - Certificates
  - Clusters
  - Dashboard Aggregates
  - Dashboards
  - GnuPGP Keys
  - GPG Keys
  - Hosts
  - Project mappings
  - Projects
  - Reconciler
  - Repositories
  - Repository Certificates
  - Repository credentials
  - ValidateHost
- name: GitX
  tags:
  - GitX Webhooks
  - Org Gitx Webhooks
  - Project Gitx Webhooks
- name: CACM
  tags:
  - Anomalies Ignorelist Rule
  - Anomalies
  - BI Dashboards
  - Budgets
  - Budget Groups
  - Cost Categories
  - Cloud Accounts
  - K8S Connectors Metadata
  - Notification Settings v2
  - Overview
  - Data Job Status
  - Recommendation cost settings
  - Unit Metric
  - Anomaly Comments
  - Cloud and AI cost anomaly details
  - Cloud and AI cost anomalies v2
  - Cost Details
  - Currency Preferences
  - External Data Provider
  - AiEngine
  - CACM governance cost settings
  - Governance Enforcement Recommendation APIs
  - Governance Alert
  - Governance Overview
  - Governance Recommendation APIs
  - RuleEnforcement
  - Rule Executions
  - Rule
  - Rule Sets
  - Perspectives Folders
  - Perspective Reports
  - Perspectives
  - Cost Category Jira Project Mapping
  - Recommendations Details
  - Recommendations
  - Recommendation Jira
  - Recommendation Preferences
  - Recommendation Presets
  - Recommendation Servicenow
  - Recommendation Tags
  - Recommendation Ignore List
  - AutoStopping Rules
  - AutoStopping Rules V2
  - AutoStopping Load Balancers
  - AutoStopping Fixed Schedules
  - AutoStopping Alerts
  - Commitment Orchestrator Events APIs
- name: Feature Flags
  tags:
  - API Keys
  - Feature Flags
  - Targets
  - Target Groups
  - Environment Perspectives
  - Anomalies
  - Proxy
  - Tags
- name: SRM
  tags:
  - Monitored Services
  - SLOs dashboard
  - NG SLOs
  - SLOs
  - Downtime
  - Srm Notification
- name: Internal Developer Portal - IDP
  tags:
  - Entities
  - Teams
  - CatalogCustomProperties
  - Scores
  - DataSource
  - KubernetesDataPoints
  - AggregationRules
  - AppConfig
  - PluginInfo
  - LayoutProxy
  - Kinds
  - LayoutsV3
  - LayoutsV4
- name: Environment Management - IDP
  tags:
  - Environment
  - Infrastructure
  - Instance
- name: Custom Dashboards
  tags:
  - aida
  - dashboards
  - downloads
  - embed
  - folders
- name: Policy Management
  tags:
  - dashboard
  - examples
  - policies
  - evaluate
  - evaluations
  - policysets
  - system
- name: Code
  tags:
  - repository
  - status_checks
  - pullreq
  - upload
  - webhook
  - resource
  - rules
  - labels
- name: IaCM
  tags:
  - usage
  - approvals
  - costs
  - executions
  - module-registry
  - workspaces
  - settings
  - tf-standard-backend
  - variables
- name: STO
  tags:
  - Exemptions
  - Issues
  - Scans
  - Products
  - Test Targets
  - Target Variants
- name: SEI
  tags:
  - Collection categories
  - Collections
  - Contributors
  - DORA
- name: Git Sync (deprecated)
  tags:
  - Git Branches
  - Git Full Sync
  - Git Sync Settings
  - Git Sync
  - Git Sync Errors
- name: Error Models
  tags:
  - Error Response
  - Governance Metadata
- name: Supply Chain Security
  tags:
  - integration
  - PipelineInfraConfig
  - SBOM
  - Integration Step Config
  - Delete Step Config
  - Delete Repositories
  - Pipeline Store Config
  - Evidence Vault [Beta]
- name: Release Management
  tags:
  - Release Groups
  - Releases
  - Orchestration Processes
  - Orchestration Activities
  - Orchestration Executions
  - Conflicts
  - Freeze
  - Reports
  - Uploads
- name: Resilience Testing
  tags:
  - Actions
  - Action Templates
  - Chaos Components
  - Chaos Hubs
  - ChaosGuard Conditions
  - ChaosGuard Rules
  - DR Tests
  - Experiments
  - Experiment Templates
  - Faults
  - Fault Templates
  - Chaos Infrastructure
  - Health
  - Network Maps
  - Onboarding
  - Probes
  - Probe Templates
  - Chaos Recommendations
  - Risks
