openapi: 3.2.0
info:
  title: Harness Target Variants API
  version: '1.0'
  description: The Harness Software Delivery Platform uses OpenAPI Specification v3.0.
  contact:
    name: API Support
    email: contact@harness.io
    url: https://harness.io/
  x-logo:
    url: https://mma.prnewswire.com/media/779232/Harnes_logo_horizontal.jpg?p=facebook
    altText: Harness
  termsOfService: https://harness.io/terms-of-use/
servers:
- url: https://app.harness.io
  description: Harness host URL
- url: https://{vanity}
  description: Vanity URL
  variables:
    vanity:
      default: app.harness.io
security:
- x-api-key: []
tags:
- name: Target Variants
  description: Access and modify Scan Target Variants
paths:
  /sto/api/v2/targets/{targetId}/variants:
    get:
      tags:
      - Target Variants
      description: List a collection of Scan Target Variants
      operationId: Target Variants#ListTargetVariants
      parameters:
      - name: accountId
        in: query
        description: Harness Account ID
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Harness Account ID
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
        example: abcdef1234567890ghijkl
      - name: page
        in: query
        description: Page number to fetch (starting from 0)
        allowEmptyValue: true
        schema:
          type: integer
          description: Page number to fetch (starting from 0)
          default: 0
          example: 4
          format: int64
          minimum: 0
        example: 4
      - name: pageSize
        in: query
        description: Number of results per page
        allowEmptyValue: true
        schema:
          type: integer
          description: Number of results per page
          default: 30
          example: 50
          format: int64
          minimum: 1
          maximum: 100
        example: 50
      - name: name
        in: query
        description: Resource name
        allowEmptyValue: true
        schema:
          type: string
          description: Resource name
          example: NodeGoat
        example: NodeGoat
      - name: targetId
        in: path
        description: Associated Target ID
        required: true
        schema:
          type: string
          description: Associated Target ID
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
        example: abcdef1234567890ghijkl
      - name: X-Api-Key
        in: header
        description: Harness personal or service access token
        allowEmptyValue: true
        schema:
          type: string
          description: Harness personal or service access token
          example: Temporibus fuga est dignissimos aspernatur nam.
        example: Voluptas et aut.
      responses:
        '200':
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoriesListRepositoryVariantsResponseBody'
              example:
                pagination:
                  link: ''
                  page: 4
                  pageSize: 20
                  totalItems: 230
                  totalPages: 12
                results:
                - created: 1651578240
                  hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
                  id: abcdef1234567890ghijkl
                  lastModified: 1651578240
                  parameters:
                    branch: main
                  targetId: abcdef1234567890ghijkl
                - created: 1651578240
                  hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
                  id: abcdef1234567890ghijkl
                  lastModified: 1651578240
                  parameters:
                    branch: main
                  targetId: abcdef1234567890ghijkl
        '400':
          description: 'BadRequest: Bad Request response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: 'Bad Request: accountId parameter is required'
                status: 400
        '401':
          description: 'Unauthorized: Unauthorized response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Unauthorized
                status: 401
        '403':
          description: 'Forbidden: Forbidden response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Forbidden
                status: 403
        '404':
          description: 'NotFound: Not Found response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Not Found
                status: 404
        '429':
          description: 'TooManyRequests: Too Many Requests response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Too Many Requests
                status: 429
        '500':
          description: 'InternalServerError: Internal Server Error response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Internal Server Error
                status: 500
      security:
      - X-Api-Key_header_X-Api-Key: []
        jwt_header_Authorization:
        - sto_testtarget_view
      summary: Target Variants#List target variants
      x-summary-source: derived
    post:
      tags:
      - Target Variants
      description: Create a new Scan Target Variant
      operationId: Target Variants#CreateTargetVariant
      parameters:
      - name: accountId
        in: query
        description: Harness Account ID
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Harness Account ID
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
        example: abcdef1234567890ghijkl
      - name: targetId
        in: path
        description: Associated Target ID
        required: true
        schema:
          type: string
          description: Associated Target ID
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
        examples:
          default:
            summary: default
            value: abcdef1234567890ghijkl
      - name: X-Api-Key
        in: header
        description: Harness personal or service access token
        allowEmptyValue: true
        schema:
          type: string
          description: Harness personal or service access token
          example: Ut tenetur et.
        example: Pariatur nisi non iure accusamus exercitationem et.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTargetVariantRequestBody'
            example:
              hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
              parameters:
                branch: main
      responses:
        '200':
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IDResult'
              example:
                id: abcdef1234567890ghijkl
        '400':
          description: 'BadRequest: Bad Request response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: 'Bad Request: accountId parameter is required'
                status: 400
        '401':
          description: 'Unauthorized: Unauthorized response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Unauthorized
                status: 401
        '403':
          description: 'Forbidden: Forbidden response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Forbidden
                status: 403
        '429':
          description: 'TooManyRequests: Too Many Requests response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Too Many Requests
                status: 429
        '500':
          description: 'InternalServerError: Internal Server Error response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Internal Server Error
                status: 500
      security:
      - X-Api-Key_header_X-Api-Key: []
        jwt_header_Authorization:
        - sto_testtarget_edit
      summary: Target Variants#Create target variant
      x-summary-source: derived
  /sto/api/v2/targets/{targetId}/variants/{id}:
    delete:
      description: Delete an existing Scan Target Variant
      operationId: Target Variants#DeleteTargetVariant
      parameters:
      - allowEmptyValue: true
        description: Harness Account ID
        example: abcdef1234567890ghijkl
        in: query
        name: accountId
        required: true
        schema:
          description: Harness Account ID
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
          type: string
      - description: Associated Target ID
        examples:
          default:
            summary: default
            value: abcdef1234567890ghijkl
        in: path
        name: targetId
        required: true
        schema:
          description: Associated Target ID
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
          type: string
      - description: The ID of the Scan Target Variant to delete
        example: abcdef1234567890ghijkl
        in: path
        name: id
        required: true
        schema:
          description: The ID of the Scan Target Variant to delete
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
          type: string
      responses:
        '204':
          description: No Content response.
        '400':
          content:
            application/json:
              example:
                message: 'Bad Request: accountId parameter is required'
                status: 400
              schema:
                $ref: '#/components/schemas/NotFound'
          description: 'BadRequest: Bad Request response.'
        '401':
          content:
            application/json:
              example:
                message: Unauthorized
                status: 401
              schema:
                $ref: '#/components/schemas/NotFound'
          description: 'Unauthorized: Unauthorized response.'
        '403':
          content:
            application/json:
              example:
                message: Forbidden
                status: 403
              schema:
                $ref: '#/components/schemas/NotFound'
          description: 'Forbidden: Forbidden response.'
        '404':
          content:
            application/json:
              example:
                message: Not Found
                status: 404
              schema:
                $ref: '#/components/schemas/NotFound'
          description: 'NotFound: Not Found response.'
        '429':
          content:
            application/json:
              example:
                message: Too Many Requests
                status: 429
              schema:
                $ref: '#/components/schemas/NotFound'
          description: 'TooManyRequests: Too Many Requests response.'
        '500':
          content:
            application/json:
              example:
                message: Internal Server Error
                status: 500
              schema:
                $ref: '#/components/schemas/NotFound'
          description: 'InternalServerError: Internal Server Error response.'
      security:
      - jwt_header_Authorization:
        - sto_testtarget_delete
      tags:
      - Target Variants
      x-internal: true
      summary: Target Variants#Delete target variant
      x-summary-source: derived
    get:
      tags:
      - Target Variants
      description: Find Scan Target Variant by ID
      operationId: Target Variants#FindTargetVariantById
      parameters:
      - name: accountId
        in: query
        description: Harness Account ID
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Harness Account ID
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
        example: abcdef1234567890ghijkl
      - name: targetId
        in: path
        description: Associated Target ID
        required: true
        schema:
          type: string
          description: Associated Target ID
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
        examples:
          default:
            summary: default
            value: abcdef1234567890ghijkl
      - name: id
        in: path
        description: The ID of the Scan Target Variant to retrieve
        required: true
        schema:
          type: string
          description: The ID of the Scan Target Variant to retrieve
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
        example: abcdef1234567890ghijkl
      - name: X-Api-Key
        in: header
        description: Harness personal or service access token
        allowEmptyValue: true
        schema:
          type: string
          description: Harness personal or service access token
          example: Rerum iure necessitatibus omnis harum tempora qui.
        example: Velit ut inventore sint qui.
      responses:
        '200':
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TargetVariant'
              example:
                created: 1651578240
                hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
                id: abcdef1234567890ghijkl
                lastModified: 1651578240
                parameters:
                  branch: main
                targetId: abcdef1234567890ghijkl
        '400':
          description: 'BadRequest: Bad Request response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: 'Bad Request: accountId parameter is required'
                status: 400
        '401':
          description: 'Unauthorized: Unauthorized response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Unauthorized
                status: 401
        '403':
          description: 'Forbidden: Forbidden response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Forbidden
                status: 403
        '404':
          description: 'NotFound: Not Found response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Not Found
                status: 404
        '429':
          description: 'TooManyRequests: Too Many Requests response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Too Many Requests
                status: 429
        '500':
          description: 'InternalServerError: Internal Server Error response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Internal Server Error
                status: 500
      security:
      - X-Api-Key_header_X-Api-Key: []
        jwt_header_Authorization:
        - sto_testtarget_view
      summary: Target Variants#Find target variant by id
      x-summary-source: derived
    put:
      tags:
      - Target Variants
      description: Update an existing Scan Target Variant
      operationId: Target Variants#UpdateTargetVariant
      parameters:
      - name: accountId
        in: query
        description: Harness Account ID
        allowEmptyValue: true
        required: true
        schema:
          type: string
          description: Harness Account ID
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
        example: abcdef1234567890ghijkl
      - name: targetId
        in: path
        description: Associated Target ID
        required: true
        schema:
          type: string
          description: Associated Target ID
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
        examples:
          default:
            summary: default
            value: abcdef1234567890ghijkl
      - name: id
        in: path
        description: The ID of the Scan Target Variant to update
        required: true
        schema:
          type: string
          description: The ID of the Scan Target Variant to update
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
        example: abcdef1234567890ghijkl
      - name: X-Api-Key
        in: header
        description: Harness personal or service access token
        allowEmptyValue: true
        schema:
          type: string
          description: Harness personal or service access token
          example: Reprehenderit adipisci aliquid veniam consequatur perferendis.
        example: Deleniti quisquam accusamus.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTargetVariantRequestBody'
            example:
              hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
              parameters:
                branch: main
      responses:
        '200':
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TargetVariant'
              example:
                created: 1651578240
                hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
                id: abcdef1234567890ghijkl
                lastModified: 1651578240
                parameters:
                  branch: main
                targetId: abcdef1234567890ghijkl
        '400':
          description: 'BadRequest: Bad Request response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: 'Bad Request: accountId parameter is required'
                status: 400
        '401':
          description: 'Unauthorized: Unauthorized response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Unauthorized
                status: 401
        '403':
          description: 'Forbidden: Forbidden response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Forbidden
                status: 403
        '404':
          description: 'NotFound: Not Found response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Not Found
                status: 404
        '429':
          description: 'TooManyRequests: Too Many Requests response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Too Many Requests
                status: 429
        '500':
          description: 'InternalServerError: Internal Server Error response.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
              example:
                message: Internal Server Error
                status: 500
      security:
      - X-Api-Key_header_X-Api-Key: []
        jwt_header_Authorization:
        - sto_testtarget_edit
      summary: Target Variants#Update target variant
      x-summary-source: derived
components:
  schemas:
    IDResult:
      type: object
      properties:
        id:
          type: string
          description: Resource identifier
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
      example:
        id: abcdef1234567890ghijkl
      required:
      - id
    RepositoriesListRepositoryVariantsResponseBody:
      type: object
      properties:
        pagination:
          $ref: '#/components/schemas/StoPagination'
        results:
          type: array
          items:
            $ref: '#/components/schemas/TargetVariant'
          example:
          - created: 1651578240
            hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
            id: abcdef1234567890ghijkl
            lastModified: 1651578240
            parameters:
              branch: main
            targetId: abcdef1234567890ghijkl
          - created: 1651578240
            hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
            id: abcdef1234567890ghijkl
            lastModified: 1651578240
            parameters:
              branch: main
            targetId: abcdef1234567890ghijkl
          - created: 1651578240
            hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
            id: abcdef1234567890ghijkl
            lastModified: 1651578240
            parameters:
              branch: main
            targetId: abcdef1234567890ghijkl
          - created: 1651578240
            hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
            id: abcdef1234567890ghijkl
            lastModified: 1651578240
            parameters:
              branch: main
            targetId: abcdef1234567890ghijkl
      example:
        pagination:
          link: ''
          page: 4
          pageSize: 20
          totalItems: 230
          totalPages: 12
        results:
        - created: 1651578240
          hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
          id: abcdef1234567890ghijkl
          lastModified: 1651578240
          parameters:
            branch: main
          targetId: abcdef1234567890ghijkl
        - created: 1651578240
          hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
          id: abcdef1234567890ghijkl
          lastModified: 1651578240
          parameters:
            branch: main
          targetId: abcdef1234567890ghijkl
      required:
      - results
      - pagination
    StoPagination:
      type: object
      properties:
        link:
          type: string
          description: Link-based paging
          example: ''
        page:
          type: integer
          description: Page number (starting from 0)
          example: 4
          format: int64
        pageSize:
          type: integer
          description: Requested page size
          example: 20
          format: int64
        totalItems:
          type: integer
          description: Total results available
          example: 230
          format: int64
        totalPages:
          type: integer
          description: Total pages available
          example: 12
          format: int64
      example:
        link: ''
        page: 4
        pageSize: 20
        totalItems: 230
        totalPages: 12
      required:
      - page
      - pageSize
      - totalPages
      - totalItems
    TargetVariant:
      type: object
      properties:
        created:
          type: integer
          description: Unix timestamp at which the resource was created
          example: 1651578240
          format: int64
        hash:
          type: string
          description: Git Commit or Container Image hash
          example: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
          maxLength: 64
        id:
          type: string
          description: Resource identifier
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
        lastModified:
          type: integer
          description: Unix timestamp at which the resource was most recently modified
          example: 1651578240
          format: int64
        parameters:
          type: object
          description: Parameters for this Variant, as a JSON-encoded string
          example:
            branch: main
          additionalProperties:
            type: string
            example: Rerum qui aliquid laboriosam atque eligendi.
        targetId:
          type: string
          description: Associated Target ID
          example: abcdef1234567890ghijkl
          pattern: ^[a-zA-Z0-9_-]{22}$
      description: Information about a Scan Target Variant
      example:
        created: 1651578240
        hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
        id: abcdef1234567890ghijkl
        lastModified: 1651578240
        parameters:
          branch: main
        targetId: abcdef1234567890ghijkl
      required:
      - targetId
      - parameters
      - id
      - created
      - lastModified
    NotFound:
      type: object
      properties:
        message:
          type: string
          example: Not Found
        status:
          type: integer
          default: 404
          example: 404
          format: int64
      example:
        message: Not Found
        status: 404
      required:
      - message
    CreateTargetVariantRequestBody:
      type: object
      properties:
        hash:
          type: string
          description: Git Commit or Container Image hash
          example: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
          maxLength: 64
        parameters:
          type: object
          description: Parameters for this Variant, as a JSON-encoded string
          example:
            branch: main
          additionalProperties:
            type: string
            example: Assumenda velit.
      example:
        hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
        parameters:
          branch: main
      required:
      - parameters
      - id
      - created
      - lastModified
    UpdateTargetVariantRequestBody:
      type: object
      properties:
        hash:
          type: string
          description: Git Commit or Container Image hash
          example: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
          maxLength: 64
        parameters:
          type: object
          description: Parameters for this Variant, as a JSON-encoded string
          example:
            branch: main
          additionalProperties:
            type: string
            example: Eum est molestiae delectus sunt asperiores ullam.
      example:
        hash: deadbeefdeadbeefdeadbeefdeadbeefdeadbeef
        parameters:
          branch: main
      required:
      - parameters
      - created
      - lastModified
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
      description: API key is a token provided while making the API calls. This is used to authenticate the client at the exposed endpoint.
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
x-stoplight:
  id: oc91t4vrfnjyi
x-tagGroups:
- name: Organizations
  tags:
  - Organization
- name: Projects
  tags:
  - Org Project
  - Project
- name: Secrets
  tags:
  - Account Secret
  - Org Secret
  - Project Secret
  - Secrets
- name: Connectors
  tags:
  - Account Connector
  - Org Connector
  - Project Connector
  - Connectors
  - GoogleSecretManagerConnector
- name: Roles
  tags:
  - Account Roles
  - Organization Roles
  - Project Roles
  - Roles
- name: Resource Groups
  tags:
  - Account Resource Groups
  - Organization Resource Groups
  - Project Resource Groups
  - Filter Resource Groups
  - Harness Resource Group
  - Zendesk
- name: Role Assignments
  tags:
  - Account Role Assignments
  - Org Role Assignments
  - Project Role Assignments
  - Role Assignments
- name: Platform
  tags:
  - Access Control List
  - Account Banner
  - Account Banner
  - Account Licensed Modules
  - Account License Type
  - Account Webhooks
  - AccountSetting
  - Accounts
  - Analyze Account Access Policy
  - Analyze Organization Access Policy
  - Analyze Project Access Policy
  - ApiKey
  - Audit
  - AuditFilters
  - Authentication Settings
  - Canny
  - Devops Essentials License Data By Account
  - EULA
  - Filter
  - Harness Resource Type
  - Invite
  - IP Allowlist
  - Nextgen Ldap
  - Notification Channels
  - Notification Rules
  - OIDC
  - Oidc-Access-Token
  - Oidc-ID-Token
  - Org Webhooks
  - Permissions
  - Project Webhooks
  - Secret Managers
  - Service Account
  - Setting
  - SMTP
  - Source Code Manager
  - Token
  - User
  - User Group
  - Variables
- name: Delegate
  tags:
  - Agent mTLS Endpoint Management
  - Delegate Download Resource
  - Delegate Group Tags Resource
  - Delegate Setup Resource
  - Delegate Token Resource
- name: Pipelines
  tags:
  - Pipelines
  - Input Sets
  - Approvals
  - Pipeline Execution
  - Pipeline Dashboard
  - Pipeline Input Set
  - Pipeline
  - Pipeline Execution Details
  - Pipeline Execute
  - Pipeline Refresh
  - Pipeline data retention
  - Triggers
  - TriggersEvents
  - Webhook Triggers
  - Webhook Event Handler
  - DryRunPipeline
- name: Artifact Registry
  tags:
  - Registries
  - Artifacts
  - Docker Artifacts
  - Helm Artifacts
  - quarantine
  - Webhooks
  - Spaces
  - Replication
  - Registry V3 - Registries
  - Registry V3 - Packages
  - Registry V3 - Versions
  - Registry V3 - Files
  - Registry V3 - Metadata
  - Registry V3 - Firewall
  - Registry V3 - Transfer
- name: Database DevOps
  tags:
  - Database Schema
  - Database Instance
  - Deployed State
  - Execution Config
  - Migration State
- name: CD
  tags:
  - K8s Release Service Mapping
  - CustomDeployment
  - Environments
  - EnvironmentGroup
  - Infrastructures
  - Usage
  - File Store
  - Service Dashboard
  - ServiceOverrides
  - Rollback
  - tas
- name: Deployment Freeze
  tags:
  - Freeze CRUD
  - Freeze Evaluation
  - Freeze Schema
- name: Services
  tags:
  - Account Services
  - Org Services
  - Project Services
  - Services
- name: Rancher Infrastructures
  tags:
  - Account Rancher Infrastructure
  - Org Rancher Infrastructure
  - Project Rancher Infrastructure
- name: Templates
  tags:
  - Account Template
  - Org Template
  - Project Template
  - Templates
  - Global Templates
- name: GitOps
  tags:
  - Agents
  - Application
  - Applications
  - Certificates
  - Clusters
  - Dashboard Aggregates
  - Dashboards
  - GnuPGP Keys
  - GPG Keys
  - Hosts
  - Project mappings
  - Projects
  - Reconciler
  - Repositories
  - Repository Certificates
  - Repository credentials
  - ValidateHost
- name: GitX
  tags:
  - GitX Webhooks
  - Org Gitx Webhooks
  - Project Gitx Webhooks
- name: CACM
  tags:
  - Anomalies Ignorelist Rule
  - Anomalies
  - BI Dashboards
  - Budgets
  - Budget Groups
  - Cost Categories
  - Cloud Accounts
  - K8S Connectors Metadata
  - Notification Settings v2
  - Overview
  - Data Job Status
  - Recommendation cost settings
  - Unit Metric
  - Anomaly Comments
  - Cloud and AI cost anomaly details
  - Cloud and AI cost anomalies v2
  - Cost Details
  - Currency Preferences
  - External Data Provider
  - AiEngine
  - CACM governance cost settings
  - Governance Enforcement Recommendation APIs
  - Governance Alert
  - Governance Overview
  - Governance Recommendation APIs
  - RuleEnforcement
  - Rule Executions
  - Rule
  - Rule Sets
  - Perspectives Folders
  - Perspective Reports
  - Perspectives
  - Cost Category Jira Project Mapping
  - Recommendations Details
  - Recommendations
  - Recommendation Jira
  - Recommendation Preferences
  - Recommendation Presets
  - Recommendation Servicenow
  - Recommendation Tags
  - Recommendation Ignore List
  - AutoStopping Rules
  - AutoStopping Rules V2
  - AutoStopping Load Balancers
  - AutoStopping Fixed Schedules
  - AutoStopping Alerts
  - Commitment Orchestrator Events APIs
- name: Feature Flags
  tags:
  - API Keys
  - Feature Flags
  - Targets
  - Target Groups
  - Environment Perspectives
  - Anomalies
  - Proxy
  - Tags
- name: SRM
  tags:
  - Monitored Services
  - SLOs dashboard
  - NG SLOs
  - SLOs
  - Downtime
  - Srm Notification
- name: Internal Developer Portal - IDP
  tags:
  - Entities
  - Teams
  - CatalogCustomProperties
  - Scores
  - DataSource
  - KubernetesDataPoints
  - AggregationRules
  - AppConfig
  - PluginInfo
  - LayoutProxy
  - Kinds
  - LayoutsV3
  - LayoutsV4
- name: Environment Management - IDP
  tags:
  - Environment
  - Infrastructure
  - Instance
- name: Custom Dashboards
  tags:
  - aida
  - dashboards
  - downloads
  - embed
  - folders
- name: Policy Management
  tags:
  - dashboard
  - examples
  - policies
  - evaluate
  - evaluations
  - policysets
  - system
- name: Code
  tags:
  - repository
  - status_checks
  - pullreq
  - upload
  - webhook
  - resource
  - rules
  - labels
- name: IaCM
  tags:
  - usage
  - approvals
  - costs
  - executions
  - module-registry
  - workspaces
  - settings
  - tf-standard-backend
  - variables
- name: STO
  tags:
  - Exemptions
  - Issues
  - Scans
  - Products
  - Test Targets
  - Target Variants
- name: SEI
  tags:
  - Collection categories
  - Collections
  - Contributors
  - DORA
- name: Git Sync (deprecated)
  tags:
  - Git Branches
  - Git Full Sync
  - Git Sync Settings
  - Git Sync
  - Git Sync Errors
- name: Error Models
  tags:
  - Error Response
  - Governance Metadata
- name: Supply Chain Security
  tags:
  - integration
  - PipelineInfraConfig
  - SBOM
  - Integration Step Config
  - Delete Step Config
  - Delete Repositories
  - Pipeline Store Config
  - Evidence Vault [Beta]
- name: Release Management
  tags:
  - Release Groups
  - Releases
  - Orchestration Processes
  - Orchestration Activities
  - Orchestration Executions
  - Conflicts
  - Freeze
  - Reports
  - Uploads
- name: Resilience Testing
  tags:
  - Actions
  - Action Templates
  - Chaos Components
  - Chaos Hubs
  - ChaosGuard Conditions
  - ChaosGuard Rules
  - DR Tests
  - Experiments
  - Experiment Templates
  - Faults
  - Fault Templates
  - Chaos Infrastructure
  - Health
  - Network Maps
  - Onboarding
  - Probes
  - Probe Templates
  - Chaos Recommendations
  - Risks
