openapi: 3.2.0
info:
  title: Harness Aida API
  version: '1.0'
  description: The Harness Software Delivery Platform uses OpenAPI Specification v3.0.
  contact:
    name: API Support
    email: contact@harness.io
    url: https://harness.io/
  x-logo:
    url: https://mma.prnewswire.com/media/779232/Harnes_logo_horizontal.jpg?p=facebook
    altText: Harness
  termsOfService: https://harness.io/terms-of-use/
servers:
- url: https://app.harness.io
  description: Harness host URL
- url: https://{vanity}
  description: Vanity URL
  variables:
    vanity:
      default: app.harness.io
security:
- x-api-key: []
tags:
- name: aida
  description: AIDA API's for Harness OPA
paths:
  /pm/api/v1/aida/accept:
    post:
      tags:
      - aida
      description: Record explicit AI acceptance from UI
      operationId: aida#accept
      parameters:
      - name: accountIdentifier
        in: query
        description: Harness account ID
        allowEmptyValue: true
        schema:
          type: string
          description: Harness account ID
          default: ''
          example: eBqAoNchMLKigC_qZ5EdC
        example: eBqAoNchMLKigC_qZ5EdC
      - name: orgIdentifier
        in: query
        description: Harness organization ID
        allowEmptyValue: true
        schema:
          type: string
          description: Harness organization ID
          default: ''
          example: test-org
        example: test-org
      - name: projectIdentifier
        in: query
        description: Harness project ID
        allowEmptyValue: true
        schema:
          type: string
          description: Harness project ID
          default: ''
          example: test-project
        example: test-project
      - name: x-api-key
        in: header
        description: Harness PAT key used to perform authorization
        allowEmptyValue: true
        schema:
          type: string
          description: Harness PAT key used to perform authorization
          example: Rerum tenetur.
        example: Blanditiis iusto.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptRequestBody'
            example:
              output: 'package policy

                ...'
              prompt: make a policy that...
      responses:
        '204':
          description: No Content response.
        '400':
          description: 'BadRequest: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '401':
          description: 'Unauthorized: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '403':
          description: 'Forbidden: Forbidden response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '404':
          description: 'NotFound: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '500':
          description: 'InternalServer: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '502':
          description: 'BadGateway: Bad Gateway response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
      security:
      - jwt_header_Authorization:
        - core_governancePolicy_view
      - api_key_header_x-api-key: []
      summary: Aida#accept
      x-summary-source: derived
  /pm/api/v1/aida/analyze:
    post:
      tags:
      - aida
      description: Describe Policy On Basis of rego
      operationId: aida#analyze
      parameters:
      - name: accountIdentifier
        in: query
        description: Harness account ID
        allowEmptyValue: true
        schema:
          type: string
          description: Harness account ID
          default: ''
          example: eBqAoNchMLKigC_qZ5EdC
        example: eBqAoNchMLKigC_qZ5EdC
      - name: orgIdentifier
        in: query
        description: Harness organization ID
        allowEmptyValue: true
        schema:
          type: string
          description: Harness organization ID
          default: ''
          example: test-org
        example: test-org
      - name: projectIdentifier
        in: query
        description: Harness project ID
        allowEmptyValue: true
        schema:
          type: string
          description: Harness project ID
          default: ''
          example: test-project
        example: test-project
      - name: x-api-key
        in: header
        description: Harness PAT key used to perform authorization
        allowEmptyValue: true
        schema:
          type: string
          description: Harness PAT key used to perform authorization
          example: Sed quae quia minima velit et vel.
        example: Blanditiis voluptatem non quis.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyzeRequestBody'
            example:
              entityType: encryptedJsonData example
              rego: query example
      responses:
        '200':
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzeResponse'
              example:
                desc: policy example
                status: SUCCESS
        '400':
          description: 'BadRequest: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '401':
          description: 'Unauthorized: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '403':
          description: 'Forbidden: Forbidden response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '404':
          description: 'NotFound: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '500':
          description: 'InternalServer: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '502':
          description: 'BadGateway: Bad Gateway response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
      security:
      - jwt_header_Authorization:
        - core_governancePolicy_view
      - api_key_header_x-api-key: []
      summary: Aida#analyze
      x-summary-source: derived
  /pm/api/v1/aida/generate:
    post:
      tags:
      - aida
      description: Generate Policy On Basis of free Text
      operationId: aida#generate
      parameters:
      - name: accountIdentifier
        in: query
        description: Harness account ID
        allowEmptyValue: true
        schema:
          type: string
          description: Harness account ID
          default: ''
          example: eBqAoNchMLKigC_qZ5EdC
        example: eBqAoNchMLKigC_qZ5EdC
      - name: orgIdentifier
        in: query
        description: Harness organization ID
        allowEmptyValue: true
        schema:
          type: string
          description: Harness organization ID
          default: ''
          example: test-org
        example: test-org
      - name: projectIdentifier
        in: query
        description: Harness project ID
        allowEmptyValue: true
        schema:
          type: string
          description: Harness project ID
          default: ''
          example: test-project
        example: test-project
      - name: x-api-key
        in: header
        description: Harness PAT key used to perform authorization
        allowEmptyValue: true
        schema:
          type: string
          description: Harness PAT key used to perform authorization
          example: Sunt est soluta quaerat rerum id.
        example: Optio ipsam ratione fuga magni.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateRequestBody'
            example:
              policyData: encryptedJsonData example
              query: query example
      responses:
        '200':
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicySample'
              example:
                policy: policy example
                status: SUCCESS
        '400':
          description: 'BadRequest: Bad Request response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '401':
          description: 'Unauthorized: Unauthorized response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '403':
          description: 'Forbidden: Forbidden response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '404':
          description: 'NotFound: Not Found response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '500':
          description: 'InternalServer: Internal Server Error response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
        '502':
          description: 'BadGateway: Bad Gateway response.'
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/PolicyManagementError'
      security:
      - jwt_header_Authorization:
        - core_governancePolicy_view
      - api_key_header_x-api-key: []
      summary: Aida#generate
      x-summary-source: derived
components:
  schemas:
    PolicyManagementError:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: true
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      example:
        fault: false
        id: 123abc
        message: parameter 'p' must be an integer
        name: bad_request
        temporary: true
        timeout: false
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    AcceptRequestBody:
      type: object
      properties:
        output:
          type: string
          description: Generated rego output
          example: 'package policy

            ...'
        prompt:
          type: string
          description: Text query
          example: make a policy that...
      example:
        output: 'package policy

          ...'
        prompt: make a policy that...
    GenerateRequestBody:
      type: object
      properties:
        policyData:
          type: string
          description: policySample Data
          example: encryptedJsonData example
        query:
          type: string
          description: Text query
          example: query example
      example:
        policyData: encryptedJsonData example
        query: query example
    PolicySample:
      type: object
      properties:
        policy:
          type: string
          description: Build identifier
          example: policy example
        status:
          type: string
          description: status
          example: SUCCESS
      description: Sample of Policy
      example:
        policy: policy example
        status: SUCCESS
      required:
      - status
      - policy
    AnalyzeRequestBody:
      type: object
      properties:
        entityType:
          type: string
          description: Type of entity on which rego is written on
          example: encryptedJsonData example
        rego:
          type: string
          description: Rego Policy
          example: query example
      example:
        entityType: encryptedJsonData example
        rego: query example
    AnalyzeResponse:
      type: object
      properties:
        desc:
          type: string
          description: Build identifier
          example: policy example
        status:
          type: string
          description: status
          example: SUCCESS
      description: Description of Policy
      example:
        desc: policy example
        status: SUCCESS
      required:
      - status
      - desc
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
      description: API key is a token provided while making the API calls. This is used to authenticate the client at the exposed endpoint.
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
x-stoplight:
  id: oc91t4vrfnjyi
x-tagGroups:
- name: Organizations
  tags:
  - Organization
- name: Projects
  tags:
  - Org Project
  - Project
- name: Secrets
  tags:
  - Account Secret
  - Org Secret
  - Project Secret
  - Secrets
- name: Connectors
  tags:
  - Account Connector
  - Org Connector
  - Project Connector
  - Connectors
  - GoogleSecretManagerConnector
- name: Roles
  tags:
  - Account Roles
  - Organization Roles
  - Project Roles
  - Roles
- name: Resource Groups
  tags:
  - Account Resource Groups
  - Organization Resource Groups
  - Project Resource Groups
  - Filter Resource Groups
  - Harness Resource Group
  - Zendesk
- name: Role Assignments
  tags:
  - Account Role Assignments
  - Org Role Assignments
  - Project Role Assignments
  - Role Assignments
- name: Platform
  tags:
  - Access Control List
  - Account Banner
  - Account Banner
  - Account Licensed Modules
  - Account License Type
  - Account Webhooks
  - AccountSetting
  - Accounts
  - Analyze Account Access Policy
  - Analyze Organization Access Policy
  - Analyze Project Access Policy
  - ApiKey
  - Audit
  - AuditFilters
  - Authentication Settings
  - Canny
  - Devops Essentials License Data By Account
  - EULA
  - Filter
  - Harness Resource Type
  - Invite
  - IP Allowlist
  - Nextgen Ldap
  - Notification Channels
  - Notification Rules
  - OIDC
  - Oidc-Access-Token
  - Oidc-ID-Token
  - Org Webhooks
  - Permissions
  - Project Webhooks
  - Secret Managers
  - Service Account
  - Setting
  - SMTP
  - Source Code Manager
  - Token
  - User
  - User Group
  - Variables
- name: Delegate
  tags:
  - Agent mTLS Endpoint Management
  - Delegate Download Resource
  - Delegate Group Tags Resource
  - Delegate Setup Resource
  - Delegate Token Resource
- name: Pipelines
  tags:
  - Pipelines
  - Input Sets
  - Approvals
  - Pipeline Execution
  - Pipeline Dashboard
  - Pipeline Input Set
  - Pipeline
  - Pipeline Execution Details
  - Pipeline Execute
  - Pipeline Refresh
  - Pipeline data retention
  - Triggers
  - TriggersEvents
  - Webhook Triggers
  - Webhook Event Handler
  - DryRunPipeline
- name: Artifact Registry
  tags:
  - Registries
  - Artifacts
  - Docker Artifacts
  - Helm Artifacts
  - quarantine
  - Webhooks
  - Spaces
  - Replication
  - Registry V3 - Registries
  - Registry V3 - Packages
  - Registry V3 - Versions
  - Registry V3 - Files
  - Registry V3 - Metadata
  - Registry V3 - Firewall
  - Registry V3 - Transfer
- name: Database DevOps
  tags:
  - Database Schema
  - Database Instance
  - Deployed State
  - Execution Config
  - Migration State
- name: CD
  tags:
  - K8s Release Service Mapping
  - CustomDeployment
  - Environments
  - EnvironmentGroup
  - Infrastructures
  - Usage
  - File Store
  - Service Dashboard
  - ServiceOverrides
  - Rollback
  - tas
- name: Deployment Freeze
  tags:
  - Freeze CRUD
  - Freeze Evaluation
  - Freeze Schema
- name: Services
  tags:
  - Account Services
  - Org Services
  - Project Services
  - Services
- name: Rancher Infrastructures
  tags:
  - Account Rancher Infrastructure
  - Org Rancher Infrastructure
  - Project Rancher Infrastructure
- name: Templates
  tags:
  - Account Template
  - Org Template
  - Project Template
  - Templates
  - Global Templates
- name: GitOps
  tags:
  - Agents
  - Application
  - Applications
  - Certificates
  - Clusters
  - Dashboard Aggregates
  - Dashboards
  - GnuPGP Keys
  - GPG Keys
  - Hosts
  - Project mappings
  - Projects
  - Reconciler
  - Repositories
  - Repository Certificates
  - Repository credentials
  - ValidateHost
- name: GitX
  tags:
  - GitX Webhooks
  - Org Gitx Webhooks
  - Project Gitx Webhooks
- name: CACM
  tags:
  - Anomalies Ignorelist Rule
  - Anomalies
  - BI Dashboards
  - Budgets
  - Budget Groups
  - Cost Categories
  - Cloud Accounts
  - K8S Connectors Metadata
  - Notification Settings v2
  - Overview
  - Data Job Status
  - Recommendation cost settings
  - Unit Metric
  - Anomaly Comments
  - Cloud and AI cost anomaly details
  - Cloud and AI cost anomalies v2
  - Cost Details
  - Currency Preferences
  - External Data Provider
  - AiEngine
  - CACM governance cost settings
  - Governance Enforcement Recommendation APIs
  - Governance Alert
  - Governance Overview
  - Governance Recommendation APIs
  - RuleEnforcement
  - Rule Executions
  - Rule
  - Rule Sets
  - Perspectives Folders
  - Perspective Reports
  - Perspectives
  - Cost Category Jira Project Mapping
  - Recommendations Details
  - Recommendations
  - Recommendation Jira
  - Recommendation Preferences
  - Recommendation Presets
  - Recommendation Servicenow
  - Recommendation Tags
  - Recommendation Ignore List
  - AutoStopping Rules
  - AutoStopping Rules V2
  - AutoStopping Load Balancers
  - AutoStopping Fixed Schedules
  - AutoStopping Alerts
  - Commitment Orchestrator Events APIs
- name: Feature Flags
  tags:
  - API Keys
  - Feature Flags
  - Targets
  - Target Groups
  - Environment Perspectives
  - Anomalies
  - Proxy
  - Tags
- name: SRM
  tags:
  - Monitored Services
  - SLOs dashboard
  - NG SLOs
  - SLOs
  - Downtime
  - Srm Notification
- name: Internal Developer Portal - IDP
  tags:
  - Entities
  - Teams
  - CatalogCustomProperties
  - Scores
  - DataSource
  - KubernetesDataPoints
  - AggregationRules
  - AppConfig
  - PluginInfo
  - LayoutProxy
  - Kinds
  - LayoutsV3
  - LayoutsV4
- name: Environment Management - IDP
  tags:
  - Environment
  - Infrastructure
  - Instance
- name: Custom Dashboards
  tags:
  - aida
  - dashboards
  - downloads
  - embed
  - folders
- name: Policy Management
  tags:
  - dashboard
  - examples
  - policies
  - evaluate
  - evaluations
  - policysets
  - system
- name: Code
  tags:
  - repository
  - status_checks
  - pullreq
  - upload
  - webhook
  - resource
  - rules
  - labels
- name: IaCM
  tags:
  - usage
  - approvals
  - costs
  - executions
  - module-registry
  - workspaces
  - settings
  - tf-standard-backend
  - variables
- name: STO
  tags:
  - Exemptions
  - Issues
  - Scans
  - Products
  - Test Targets
  - Target Variants
- name: SEI
  tags:
  - Collection categories
  - Collections
  - Contributors
  - DORA
- name: Git Sync (deprecated)
  tags:
  - Git Branches
  - Git Full Sync
  - Git Sync Settings
  - Git Sync
  - Git Sync Errors
- name: Error Models
  tags:
  - Error Response
  - Governance Metadata
- name: Supply Chain Security
  tags:
  - integration
  - PipelineInfraConfig
  - SBOM
  - Integration Step Config
  - Delete Step Config
  - Delete Repositories
  - Pipeline Store Config
  - Evidence Vault [Beta]
- name: Release Management
  tags:
  - Release Groups
  - Releases
  - Orchestration Processes
  - Orchestration Activities
  - Orchestration Executions
  - Conflicts
  - Freeze
  - Reports
  - Uploads
- name: Resilience Testing
  tags:
  - Actions
  - Action Templates
  - Chaos Components
  - Chaos Hubs
  - ChaosGuard Conditions
  - ChaosGuard Rules
  - DR Tests
  - Experiments
  - Experiment Templates
  - Faults
  - Fault Templates
  - Chaos Infrastructure
  - Health
  - Network Maps
  - Onboarding
  - Probes
  - Probe Templates
  - Chaos Recommendations
  - Risks
