openapi: 3.2.0
info:
  title: Harness Project Secret API
  version: '1.0'
  description: The Harness Software Delivery Platform uses OpenAPI Specification v3.0.
  contact:
    name: API Support
    email: contact@harness.io
    url: https://harness.io/
  x-logo:
    url: https://mma.prnewswire.com/media/779232/Harnes_logo_horizontal.jpg?p=facebook
    altText: Harness
  termsOfService: https://harness.io/terms-of-use/
servers:
- url: https://app.harness.io
  description: Harness host URL
- url: https://{vanity}
  description: Vanity URL
  variables:
    vanity:
      default: app.harness.io
security:
- x-api-key: []
tags:
- name: Project Secret
  description: This contains APIs for project-scoped secrets.
  x-displayName: Project Secrets [Beta]
paths:
  /v1/orgs/{org}/projects/{project}/secrets:
    parameters:
    - $ref: '#/components/parameters/OrgPathParam'
    - $ref: '#/components/parameters/ProjectPathParam'
    post:
      summary: Create a secret
      operationId: create-project-scoped-secret
      responses:
        '201':
          $ref: '#/components/responses/SecretResponse'
      description: Creates a new secret
      requestBody:
        $ref: '#/components/requestBodies/SecretRequest'
      parameters:
      - $ref: '#/components/parameters/PrivateSecret'
      - $ref: '#/components/parameters/AccountHeader'
      tags:
      - Project Secret
      security:
      - x-api-key: []
    get:
      summary: List secrets
      operationId: get-project-scoped-secrets
      responses:
        '200':
          $ref: '#/components/responses/SecretListResponse'
      description: Retrieves the information of the secrets.
      parameters:
      - schema:
          type: array
          items:
            type: string
        in: query
        name: secret
        description: Identifier field of secrets
      - schema:
          type: array
          items:
            type: string
            enum:
            - SSHKeyPath
            - SSHKeyReference
            - SSHPassword
            - SSHKerberosTGTKeyTabFile
            - SSHKerberosTGTPassword
            - SecretFile
            - SecretText
            - WinRmTGTKeyTabFile
            - WinRmTGTPassword
            - WinRmNTLM
        in: query
        name: type
        description: Secret types on which the filter will be applied
      - schema:
          type: boolean
          default: false
        in: query
        name: recursive
        description: 'Expand current scope to include all child scopes '
      - $ref: '#/components/parameters/SearchTerm1'
      - $ref: '#/components/parameters/Page'
      - $ref: '#/components/parameters/Limit1'
      - $ref: '#/components/parameters/AccountHeader'
      - $ref: '#/components/parameters/Sort1'
      - $ref: '#/components/parameters/Order'
      tags:
      - Project Secret
      security:
      - x-api-key: []
  /v1/orgs/{org}/projects/{project}/secrets/validate-secret-ref:
    parameters:
    - schema:
        type: string
      name: org
      in: path
      required: true
      description: Identifier field of the organization the resource is scoped to
    - schema:
        type: string
      name: project
      in: path
      required: true
      description: Identifier field of the project to which the resource is scoped.
    post:
      summary: Validate secret reference
      operationId: validate-project-secret-ref
      description: Validates if the secret at the secretManager path can be referenced
      parameters:
      - $ref: '#/components/parameters/AccountHeader'
      security:
      - x-api-key: []
      requestBody:
        $ref: '#/components/requestBodies/SecretValidationRequest'
      responses:
        '200':
          $ref: '#/components/responses/SecretValidationResponse'
      tags:
      - Project Secret
  /v1/orgs/{org}/projects/{project}/secrets/{secret}:
    parameters:
    - $ref: '#/components/parameters/OrgPathParam'
    - $ref: '#/components/parameters/ProjectPathParam'
    - schema:
        type: string
      name: secret
      in: path
      required: true
      description: Identifier field of the secret
    get:
      summary: Retrieve a secret
      tags:
      - Project Secret
      responses:
        '200':
          $ref: '#/components/responses/SecretResponse'
      operationId: get-project-scoped-secret
      description: Retrieves the information of the secret.
      parameters:
      - $ref: '#/components/parameters/AccountHeader'
      security:
      - x-api-key: []
    delete:
      summary: Delete a secret
      tags:
      - Project Secret
      operationId: delete-project-scoped-secret
      responses:
        '200':
          $ref: '#/components/responses/SecretResponse'
      description: Deletes the information of the secret with the matching secret identifier.
      parameters:
      - $ref: '#/components/parameters/AccountHeader'
      security:
      - x-api-key: []
    put:
      summary: Update a secret
      operationId: update-project-scoped-secret
      responses:
        '200':
          $ref: '#/components/responses/SecretResponse'
      description: Updates the information of the secret with the matching secret identifier.
      parameters:
      - $ref: '#/components/parameters/AccountHeader'
      requestBody:
        $ref: '#/components/requestBodies/SecretRequest'
      tags:
      - Project Secret
      security:
      - x-api-key: []
components:
  schemas:
    SecretSpec:
      title: SecretSpec
      type: object
      description: Details of the secret defined in Harness
      required:
      - type
      discriminator:
        propertyName: type
        mapping:
          SSHKeyPath: '#/components/schemas/SSHKeyPathSpec'
          SSHKeyReference: '#/components/schemas/SSHKeyReferenceSpec'
          SSHPassword: '#/components/schemas/SSHPasswordSpec'
          SSHKerberosTGTKeyTabFile: '#/components/schemas/SSHKerberosTGTKeyTabFileSpec'
          SSHKerberosTGTPassword: '#/components/schemas/SSHKerberosTGTPasswordSpec'
          SecretFile: '#/components/schemas/SecretFileSpec'
          SecretText: '#/components/schemas/SecretTextSpec'
          WinRmTGTKeyTabFile: '#/components/schemas/WinRmTGTKeyTabFileSpec'
          WinRmTGTPassword: '#/components/schemas/WinRmTGTPasswordSpec'
          WinRmNTLM: '#/components/schemas/WinRmNTLMSpec'
      properties:
        type:
          type: string
          enum:
          - SSHKeyPath
          - SSHKeyReference
          - SSHPassword
          - SSHKerberosTGTKeyTabFile
          - SSHKerberosTGTPassword
          - SecretFile
          - SecretText
          - WinRmTGTKeyTabFile
          - WinRmTGTPassword
          - WinRmNTLM
          description: This specifies the type of secret
    Secret:
      type: object
      properties:
        name:
          type: string
          description: Secret name
          pattern: ^[0-9a-zA-Z-_ ]{0,127}$
        identifier:
          type: string
          minLength: 1
          pattern: ^[a-zA-Z_][0-9a-zA-Z_$-]{0,127}$
          description: Secret identifier
          maxLength: 128
        org:
          type: string
          description: Organization identifier for secret
          pattern: ^[a-zA-Z_][0-9a-zA-Z-_ ]{0,127}$
        project:
          type: string
          description: Project identifier for secret
          pattern: ^[a-zA-Z_][0-9a-zA-Z-_ ]{0,127}$
        tags:
          type: object
          additionalProperties:
            type: string
          description: Secret tags
        description:
          type: string
          description: Secret description
        spec:
          $ref: '#/components/schemas/SecretSpec'
      required:
      - name
      - identifier
      - spec
    SecretRequest:
      type: object
      properties:
        secret:
          $ref: '#/components/schemas/Secret'
      required:
      - secret
    SecretResponse:
      title: SecretResponse
      type: object
      properties:
        secret:
          $ref: '#/components/schemas/Secret'
        created:
          type: integer
          format: int64
          description: Creation timestamp for the secret
        updated:
          type: integer
          format: int64
          description: Updated timestamp for the secret
        draft:
          type: boolean
        governance_metadata:
          type: object
          description: Governance metadata information
      description: Secret response model
    SecretValidationResponse:
      title: SecretValidationResponse
      type: object
      description: Response of the secret reference validation
      properties:
        success:
          type: boolean
        message:
          type: string
          description: Secret reference path validation result
  responses:
    SecretResponse:
      description: Secret response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SecretResponse'
          examples:
            example-secret-response-json:
              value:
                secret:
                  name: example_secret
                  identifier: example_secret
                  org: default
                  project: example_project
                  tags:
                    property1: example_secret
                  description: example_secret
                  spec:
                    type: SSHKeyPath
                    port: 80
                    username: example_secret
                    key_path: example_secret
                    encrypted_passphrase: account.example_secret
                created: 1234567890
                updated: 1234567890
                draft: false
        application/yaml:
          schema:
            $ref: '#/components/schemas/SecretResponse'
          examples:
            example-secret-response-yaml:
              value: "secret:\n  name: example_secret\n  identifier: example_secret\n  org: default\n  project: example_project\n  tags:\n    property1: example_secret\n  description: example_secret\n  spec:\n    type: SSHKeyPath\n    port: 80\n    username: example_secret\n    key_path: example_secret\n    encrypted_passphrase: account.example_secret\ncreated: 1234567890\nupdated: 1234567890\ndraft: false\n"
    SecretValidationResponse:
      description: 'Response of the secret reference validation '
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SecretValidationResponse'
          examples:
            Example 1:
              value:
                success: true
                message: Validation is Successful, Secret can be referenced
    SecretListResponse:
      description: Secret list response
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SecretResponse'
          examples:
            example-list-secret-response-json:
              value:
              - secret:
                  name: example_secret
                  identifier: example_secret
                  org: default
                  project: example_project
                  tags:
                    property1: example_secret
                  description: example_secret
                  spec:
                    type: SSHKeyPath
                    port: 80
                    username: example_secret
                    key_path: example_secret
                    encrypted_passphrase: account.example_secret
                created: 1234567890
                updated: 1234567890
                draft: false
        application/yaml:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/SecretResponse'
          examples:
            example-list-secret-response-yaml:
              value: "- secret:\n    name: example_secret\n    identifier: example_secret\n    org: default\n    project: example_project\n    tags:\n      property1: example_secret\n    description: example_secret\n    spec:\n      type: SSHKeyPath\n      port: 80\n      username: example_secret\n      key_path: example_secret\n      encrypted_passphrase: account.example_secret\n  created: 1234567890\n  updated: 1234567890\n  draft: false\n"
      headers:
        X-Total-Elements:
          schema:
            type: integer
          description: Total number of elements returned in Paginated response.
        X-Page-Number:
          schema:
            type: integer
          description: Page number in Paginated response.
        X-Page-Size:
          schema:
            type: integer
          description: Maximum page size in Paginated response.
  requestBodies:
    SecretValidationRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SecretRequest'
          examples:
            Example 1:
              value:
                secret_manager_identifier: prod_sm_one
                secret_ref_path: path1/path2#key
      description: Details of the secret reference
    SecretRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SecretRequest'
          examples:
            example-ssh-kerberos-tgt-key-tab-file-secret-request-json:
              value:
                secret:
                  name: example_secret
                  identifier: example_secret
                  org: default
                  project: example_project
                  tags:
                    property1: example_secret
                  description: example_secret
                  spec:
                    type: SSHKerberosTGTKeyTabFile
                    port: 22
                    principal: example-principal
                    realm: example-realm
                    key_path: key/file/path
            example-ssh-kerberos-tgt-password-secret-request-json:
              value:
                secret:
                  name: example_secret
                  identifier: example_secret
                  org: default
                  project: example_project
                  tags:
                    property1: example_secret
                  description: example_secret
                  spec:
                    type: SSHKerberosTGTPassword
                    port: 22
                    principal: example-principal
                    realm: example-realm
                    password: account.example-password
            example-secret-file-secret-request-json:
              value:
                secret:
                  name: example_secret
                  identifier: example_secret
                  org: default
                  project: example_project
                  tags:
                    property1: example_secret
                  description: example_secret
                  spec:
                    type: SecretFile
                    secret_manager_identifier: example_secret_manager_identifier
            example-secret-text-secret-request-json:
              value:
                secret:
                  name: example_secret
                  identifier: example_secret
                  org: default
                  project: example_project
                  tags:
                    property1: example_secret
                  description: example_secret
                  spec:
                    type: SecretText
                    secret_manager_identifier: example_secret_manager_identifier
                    value_type: Inline
                    value: example_secret_text_value
            example-ssh-key-path-file-secret-request-json:
              value:
                secret:
                  name: example_secret
                  identifier: example_secret
                  org: default
                  project: example_project
                  tags:
                    property1: example_secret
                  description: example_secret
                  spec:
                    type: SSHKeyPath
                    port: 22
                    username: example_username
                    key_path: ssh/key/path
                    encrypted_passphrase: account.example_passphrase
            example-ssh-key-reference-secret-request-json:
              value:
                secret:
                  name: example_secret
                  identifier: example_secret
                  org: default
                  project: example_project
                  tags:
                    property1: example_secret
                  description: example_secret
                  spec:
                    type: SSHKeyReference
                    port: 22
                    username: example_username
                    key: example/secret/key/path
                    encrypted_passphrase: account.example_passphrase
            example-ssh-password-secret-request-json:
              value:
                secret:
                  name: example_secret
                  identifier: example_secret
                  org: default
                  project: example_project
                  tags:
                    property1: example_secret
                  description: example_secret
                  spec:
                    type: SSHPassword
                    port: 22
                    username: example_username
                    password: account.example_password
            example-winrm-ntlm-secret-request-json:
              value:
                secret:
                  name: example_secret
                  identifier: example_secret
                  org: default
                  project: example_project
                  tags:
                    property1: example_secret
                  description: example_secret
                  spec:
                    type: WinRmNTLM
                    port: 5986
                    domain: example-domain
                    username: example-username
                    password: example-password
                    use_ssl: true
                    skip_cert_checks: true
                    use_no_profile: true
            example-winrm-tgt-key-file-tab-secret-request-json:
              value:
                secret:
                  name: example_secret
                  identifier: example_secret
                  org: default
                  project: example_project
                  tags:
                    property1: example_secret
                  description: example_secret
                  spec:
                    type: WinRmTGTKeyTabFile
                    port: 5986
                    principal: example-principal
                    realm: example-realm
                    key_path: key/file/path
                    use_ssl: true
                    skip_cert_checks: true
                    use_no_profile: true
            example-winrm-tgt-password-secret-request-json:
              value:
                secret:
                  name: example_secret
                  identifier: example_secret
                  org: default
                  project: example_project
                  tags:
                    property1: example_secret
                  description: example_secret
                  spec:
                    type: WinRmTGTPassword
                    port: 5986
                    principal: example-principal
                    realm: example-realm
                    password: example-password
                    use_ssl: true
                    skip_cert_checks: true
                    use_no_profile: true
        application/yaml:
          schema:
            $ref: '#/components/schemas/SecretRequest'
          examples:
            example-ssh-kerberos-tgt-key-tab-file-secret-request-yaml:
              value: "secret:\n  name: example_secret\n  identifier: example_secret\n  org: default\n  project: example_project\n  tags:\n    property1: example_secret\n  description: example_secret\n  spec:\n    type: SSHKerberosTGTKeyTabFile\n    port: 22\n    principal: example-principal\n    realm: example-realm\n    key_path: key/file/path\n"
            example-ssh-kerberos-tgt-password-secret-request-yaml:
              value: "secret:\n  name: example_secret\n  identifier: example_secret\n  org: default\n  project: example_project\n  tags:\n    property1: example_secret\n  description: example_secret\n  spec:\n    type: SSHKerberosTGTPassword\n    port: 22\n    principal: example-principal\n    realm: example-realm\n    password: account.example-password\n"
            example-secret-file-secret-request-yaml:
              value: "secret:\n  name: example_secret\n  identifier: example_secret\n  org: default\n  project: example_project\n  tags:\n    property1: example_secret\n  description: example_secret\n  spec:\n    type: SecretFile\n    secret_manager_identifier: example_secret_manager_identifier\n"
            example-secret-text-secret-request-yaml:
              value: "secret:\n  name: example_secret\n  identifier: example_secret\n  org: default\n  project: example_project\n  tags:\n    property1: example_secret\n  description: example_secret\n  spec:\n    type: SecretText\n    secret_manager_identifier: example_secret_manager_identifier\n    value_type: Inline\n    value: example_secret_text_value\n"
            example-ssh-key-path-file-secret-request-yaml:
              value: "secret:\n  name: example_secret\n  identifier: example_secret\n  org: default\n  project: example_project\n  tags:\n    property1: example_secret\n  description: example_secret\n  spec:\n    type: SSHKeyPath\n    port: 22\n    username: example_username\n    key_path: ssh/key/path\n    encrypted_passphrase: account.example_passphrase\n"
            example-ssh-key-reference-secret-request-yaml:
              value: "secret:\n  name: example_secret\n  identifier: example_secret\n  org: default\n  project: example_project\n  tags:\n    property1: example_secret\n  description: example_secret\n  spec:\n    type: SSHKeyReference\n    port: 22\n    username: example_username\n    key: example/secret/key/path\n    encrypted_passphrase: account.example_passphrase\n"
            example-ssh-password-secret-request-yaml:
              value: "secret:\n  name: example_secret\n  identifier: example_secret\n  org: default\n  project: example_project\n  tags:\n    property1: example_secret\n  description: example_secret\n  spec:\n    type: SSHPassword\n    port: 22\n    username: example_username\n    password: account.example_password\n"
            example-winrm-ntlm-secret-request-yaml:
              value: "secret:\n  name: example_secret\n  identifier: example_secret\n  org: default\n  project: example_project\n  tags:\n    property1: example_secret\n  description: example_secret\n  spec:\n    type: WinRmNTLM\n    port: 5986\n    domain: example-domain\n    username: example-username\n    password: example-password\n    use_ssl: true\n    skip_cert_checks: true\n    use_no_profile: true\n"
            example-winrm-tgt-key-file-tab-secret-request-yaml:
              value: "secret:\n  name: example_secret\n  identifier: example_secret\n  org: default\n  project: example_project\n  tags:\n    property1: example_secret\n  description: example_secret\n  spec:\n    type: WinRmTGTKeyTabFile\n    port: 5986\n    principal: example-principal\n    realm: example-realm\n    key_path: key/file/path\n    use_ssl: true\n    skip_cert_checks: true\n    use_no_profile: true\n"
            example-winrm-tgt-password-secret-request-yaml:
              value: "secret:\n  name: example_secret\n  identifier: example_secret\n  org: default\n  project: example_project\n  tags:\n    property1: example_secret\n  description: example_secret\n  spec:\n    type: WinRmTGTPassword\n    port: 5986\n    principal: example-principal\n    realm: example-realm\n    password: example-password\n    use_ssl: true\n    skip_cert_checks: true\n    use_no_profile: true\n"
        multipart/form-data:
          schema:
            properties:
              spec:
                $ref: '#/components/schemas/SecretRequest'
              file:
                type: string
                format: binary
            required:
            - file
            - spec
          encoding:
            spec:
              contentType: application/json
      required: true
  parameters:
    SearchTerm1:
      name: search_term
      in: query
      required: false
      schema:
        type: string
      description: This would be used to filter resources having attributes matching with search term.
    PrivateSecret:
      name: private_secret
      in: query
      schema:
        type: boolean
        default: false
      description: This would be used to define secret as private.
    ProjectPathParam:
      name: project
      in: path
      required: true
      schema:
        type: string
      description: Identifier field of the project the resource is scoped to
    Sort1:
      name: sort
      in: query
      required: false
      schema:
        type: string
        enum:
        - name
        - identifier
        - created
        - updated
      description: Parameter on the basis of which sorting is done.
    OrgPathParam:
      name: org
      in: path
      required: true
      schema:
        type: string
      description: Identifier field of the organization the resource is scoped to
    AccountHeader:
      name: Harness-Account
      in: header
      required: false
      schema:
        type: string
      description: Identifier field of the account the resource is scoped to. This is required for Authorization methods other than the x-api-key header. If you are using the x-api-key header, this can be skipped.
    Order:
      name: order
      in: query
      required: false
      schema:
        type: string
        enum:
        - ASC
        - DESC
      description: Order on the basis of which sorting is done.
    Page:
      name: page
      in: query
      required: false
      schema:
        type: integer
        default: 0
      description: "Pagination page number strategy: Specify the page number within the paginated collection related to the number of items in each page\t"
    Limit1:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        default: 20
        maximum: 1000
      description: Number of items to return per page.
  securitySchemes:
    x-api-key:
      name: x-api-key
      type: apiKey
      in: header
      description: API key is a token provided while making the API calls. This is used to authenticate the client at the exposed endpoint.
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
x-stoplight:
  id: oc91t4vrfnjyi
x-tagGroups:
- name: Organizations
  tags:
  - Organization
- name: Projects
  tags:
  - Org Project
  - Project
- name: Secrets
  tags:
  - Account Secret
  - Org Secret
  - Project Secret
  - Secrets
- name: Connectors
  tags:
  - Account Connector
  - Org Connector
  - Project Connector
  - Connectors
  - GoogleSecretManagerConnector
- name: Roles
  tags:
  - Account Roles
  - Organization Roles
  - Project Roles
  - Roles
- name: Resource Groups
  tags:
  - Account Resource Groups
  - Organization Resource Groups
  - Project Resource Groups
  - Filter Resource Groups
  - Harness Resource Group
  - Zendesk
- name: Role Assignments
  tags:
  - Account Role Assignments
  - Org Role Assignments
  - Project Role Assignments
  - Role Assignments
- name: Platform
  tags:
  - Access Control List
  - Account Banner
  - Account Banner
  - Account Licensed Modules
  - Account License Type
  - Account Webhooks
  - AccountSetting
  - Accounts
  - Analyze Account Access Policy
  - Analyze Organization Access Policy
  - Analyze Project Access Policy
  - ApiKey
  - Audit
  - AuditFilters
  - Authentication Settings
  - Canny
  - Devops Essentials License Data By Account
  - EULA
  - Filter
  - Harness Resource Type
  - Invite
  - IP Allowlist
  - Nextgen Ldap
  - Notification Channels
  - Notification Rules
  - OIDC
  - Oidc-Access-Token
  - Oidc-ID-Token
  - Org Webhooks
  - Permissions
  - Project Webhooks
  - Secret Managers
  - Service Account
  - Setting
  - SMTP
  - Source Code Manager
  - Token
  - User
  - User Group
  - Variables
- name: Delegate
  tags:
  - Agent mTLS Endpoint Management
  - Delegate Download Resource
  - Delegate Group Tags Resource
  - Delegate Setup Resource
  - Delegate Token Resource
- name: Pipelines
  tags:
  - Pipelines
  - Input Sets
  - Approvals
  - Pipeline Execution
  - Pipeline Dashboard
  - Pipeline Input Set
  - Pipeline
  - Pipeline Execution Details
  - Pipeline Execute
  - Pipeline Refresh
  - Pipeline data retention
  - Triggers
  - TriggersEvents
  - Webhook Triggers
  - Webhook Event Handler
  - DryRunPipeline
- name: Artifact Registry
  tags:
  - Registries
  - Artifacts
  - Docker Artifacts
  - Helm Artifacts
  - quarantine
  - Webhooks
  - Spaces
  - Replication
  - Registry V3 - Registries
  - Registry V3 - Packages
  - Registry V3 - Versions
  - Registry V3 - Files
  - Registry V3 - Metadata
  - Registry V3 - Firewall
  - Registry V3 - Transfer
- name: Database DevOps
  tags:
  - Database Schema
  - Database Instance
  - Deployed State
  - Execution Config
  - Migration State
- name: CD
  tags:
  - K8s Release Service Mapping
  - CustomDeployment
  - Environments
  - EnvironmentGroup
  - Infrastructures
  - Usage
  - File Store
  - Service Dashboard
  - ServiceOverrides
  - Rollback
  - tas
- name: Deployment Freeze
  tags:
  - Freeze CRUD
  - Freeze Evaluation
  - Freeze Schema
- name: Services
  tags:
  - Account Services
  - Org Services
  - Project Services
  - Services
- name: Rancher Infrastructures
  tags:
  - Account Rancher Infrastructure
  - Org Rancher Infrastructure
  - Project Rancher Infrastructure
- name: Templates
  tags:
  - Account Template
  - Org Template
  - Project Template
  - Templates
  - Global Templates
- name: GitOps
  tags:
  - Agents
  - Application
  - Applications
  - Certificates
  - Clusters
  - Dashboard Aggregates
  - Dashboards
  - GnuPGP Keys
  - GPG Keys
  - Hosts
  - Project mappings
  - Projects
  - Reconciler
  - Repositories
  - Repository Certificates
  - Repository credentials
  - ValidateHost
- name: GitX
  tags:
  - GitX Webhooks
  - Org Gitx Webhooks
  - Project Gitx Webhooks
- name: CACM
  tags:
  - Anomalies Ignorelist Rule
  - Anomalies
  - BI Dashboards
  - Budgets
  - Budget Groups
  - Cost Categories
  - Cloud Accounts
  - K8S Connectors Metadata
  - Notification Settings v2
  - Overview
  - Data Job Status
  - Recommendation cost settings
  - Unit Metric
  - Anomaly Comments
  - Cloud and AI cost anomaly details
  - Cloud and AI cost anomalies v2
  - Cost Details
  - Currency Preferences
  - External Data Provider
  - AiEngine
  - CACM governance cost settings
  - Governance Enforcement Recommendation APIs
  - Governance Alert
  - Governance Overview
  - Governance Recommendation APIs
  - RuleEnforcement
  - Rule Executions
  - Rule
  - Rule Sets
  - Perspectives Folders
  - Perspective Reports
  - Perspectives
  - Cost Category Jira Project Mapping
  - Recommendations Details
  - Recommendations
  - Recommendation Jira
  - Recommendation Preferences
  - Recommendation Presets
  - Recommendation Servicenow
  - Recommendation Tags
  - Recommendation Ignore List
  - AutoStopping Rules
  - AutoStopping Rules V2
  - AutoStopping Load Balancers
  - AutoStopping Fixed Schedules
  - AutoStopping Alerts
  - Commitment Orchestrator Events APIs
- name: Feature Flags
  tags:
  - API Keys
  - Feature Flags
  - Targets
  - Target Groups
  - Environment Perspectives
  - Anomalies
  - Proxy
  - Tags
- name: SRM
  tags:
  - Monitored Services
  - SLOs dashboard
  - NG SLOs
  - SLOs
  - Downtime
  - Srm Notification
- name: Internal Developer Portal - IDP
  tags:
  - Entities
  - Teams
  - CatalogCustomProperties
  - Scores
  - DataSource
  - KubernetesDataPoints
  - AggregationRules
  - AppConfig
  - PluginInfo
  - LayoutProxy
  - Kinds
  - LayoutsV3
  - LayoutsV4
- name: Environment Management - IDP
  tags:
  - Environment
  - Infrastructure
  - Instance
- name: Custom Dashboards
  tags:
  - aida
  - dashboards
  - downloads
  - embed
  - folders
- name: Policy Management
  tags:
  - dashboard
  - examples
  - policies
  - evaluate
  - evaluations
  - policysets
  - system
- name: Code
  tags:
  - repository
  - status_checks
  - pullreq
  - upload
  - webhook
  - resource
  - rules
  - labels
- name: IaCM
  tags:
  - usage
  - approvals
  - costs
  - executions
  - module-registry
  - workspaces
  - settings
  - tf-standard-backend
  - variables
- name: STO
  tags:
  - Exemptions
  - Issues
  - Scans
  - Products
  - Test Targets
  - Target Variants
- name: SEI
  tags:
  - Collection categories
  - Collections
  - Contributors
  - DORA
- name: Git Sync (deprecated)
  tags:
  - Git Branches
  - Git Full Sync
  - Git Sync Settings
  - Git Sync
  - Git Sync Errors
- name: Error Models
  tags:
  - Error Response
  - Governance Metadata
- name: Supply Chain Security
  tags:
  - integration
  - PipelineInfraConfig
  - SBOM
  - Integration Step Config
  - Delete Step Config
  - Delete Repositories
  - Pipeline Store Config
  - Evidence Vault [Beta]
- name: Release Management
  tags:
  - Release Groups
  - Releases
  - Orchestration Processes
  - Orchestration Activities
  - Orchestration Executions
  - Conflicts
  - Freeze
  - Reports
  - Uploads
- name: Resilience Testing
  tags:
  - Actions
  - Action Templates
  - Chaos Components
  - Chaos Hubs
  - ChaosGuard Conditions
  - ChaosGuard Rules
  - DR Tests
  - Experiments
  - Experiment Templates
  - Faults
  - Fault Templates
  - Chaos Infrastructure
  - Health
  - Network Maps
  - Onboarding
  - Probes
  - Probe Templates
  - Chaos Recommendations
  - Risks
